Feat/lesson listing description
oaknational/Oak-Web-Application pull request #1762
Opened 2023-07-27 10:45 UTC by k-huggs

## Description

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

2023-07-27 15:31 UTC, jack-skerrett-oak requested changes
- I don't think it matters to anyone, but there is an empty div which seems to be the div that the description would go in if it was there (live on OWA at the moment it has a span inside it as well!)
![Screenshot 2023-07-27 at 16 15 49](https://github.com/oaknational/Oak-Web-Application/assets/102532470/2de091b6-5194-4d5c-81b8-39ba6c164917)

2023-07-27 15:31 UTC, jack-skerrett-oak approved these changes

2023-07-27 15:50 UTC, k-huggs commented
> * I don't think it matters to anyone, but there is an empty div which seems to be the div that the description would go in if it was there (live on OWA at the moment it has a span inside it as well!)
>   ![Screenshot 2023-07-27 at 16 15 49](https://user-images.githubusercontent.com/102532470/256583045-2de091b6-5194-4d5c-81b8-39ba6c164917.png)

Should be fixed now

2023-07-28 08:45 UTC, kimon-satan approved these changes

2023-07-28 09:18 UTC, merged

2023-07-28 09:20 UTC, oak-machine-user commented
:tada: This PR is included in version 1.205.1 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.205.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: