Feat/styled lesson details component
oaknational/Oak-Web-Application pull request #1781
Opened 2023-08-08 10:14 UTC by k-huggs

## Description

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

2023-08-09 08:22 UTC, jack-skerrett-oak requested changes
Tiniest of changes. 
- Could the gap between the title and body text here be increased ever so slightly. The designs make it to be 8px I think? Just looks a bit cramped at the moment
![Screenshot 2023-08-09 at 09 12 55](https://github.com/oaknational/Oak-Web-Application/assets/102532470/a15b6a8d-5eb7-403a-8ba2-cea57084318b)
- Could the "Equipment" and "Content guidance" titles be changed to h3s? They aren't within key words so should maintain the same heading level as all the other sections imo
- Could the items under "content guidance" be part of a ul if there is more than one?

2023-08-09 10:32 UTC, kimon-satan requested changes
Lets have a brief chat about that styled box

2023-08-10 11:13 UTC, k-huggs commented on src/components/LessonDetails/LessonDetails.tsx
> +  // can't set margin-bottom to 0px on the last child because of the lint rule
We don't know which lesson will have which resources, so wanted to use the last-child pseudo class. 
Ignored the linting rul

2023-08-10 12:06 UTC, jack-skerrett-oak approved these changes

2023-08-10 13:23 UTC, kimon-satan approved these changes

2023-08-10 13:46 UTC, merged

2023-08-10 13:49 UTC, oak-machine-user commented
:tada: This PR is included in version 1.216.4 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.216.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: