Feat/year label unit listing
oaknational/Oak-Web-Application pull request #1794
Opened 2023-08-16 14:43 UTC by k-huggs

## Description

- Adds year group to Optionality Card

## Issue(s)

Fixes # LESQ-211

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):

![Screenshot 2023-08-15 at 17 45 51](https://github.com/oaknational/Oak-Web-Application/assets/91190841/20f9435d-a530-48f9-bd80-1465d9660dd0)

How it should now look:

<img width="910" alt="Screenshot 2023-08-16 at 15 41 47" src="https://github.com/oaknational/Oak-Web-Application/assets/91190841/51bc0fa8-2d1a-41a7-8e8d-c399fa19abc6">

<img width="409" alt="Screenshot 2023-08-16 at 15 42 18" src="https://github.com/oaknational/Oak-Web-Application/assets/91190841/e9603e15-80db-4e3b-ac93-ee0c5bc2bf21">

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

2023-08-16 16:25 UTC, jack-skerrett-oak requested changes
- They will need to be something other than <h6>, ruins the semantic HTML-ness having them as <h6>s

Also a bit odd, but a screen reader is reading "Heading level 6, year 10" twice... not sure why

2023-08-17 07:57 UTC, jack-skerrett-oak approved these changes

2023-08-17 11:16 UTC, JBR90 approved these changes
LGTM

2023-08-17 11:32 UTC, merged

2023-08-17 11:35 UTC, oak-machine-user commented
:tada: This PR is included in version 1.220.1 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.220.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: