Feat/key stage style subject listing
oaknational/Oak-Web-Application pull request #1799
Opened 2023-08-18 14:02 UTC by k-huggs

## Description

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

2023-08-21 12:08 UTC, jack-skerrett-oak requested changes
Semantic HTML thing:
- They shouldn't be h3 and h4 tags as they come before the h1 tag (which means the page order is now h3, h4, h1 which is confusing). Not sure how you handle the h3 because that is a h3 on another page, but the h4s don't need to be headings on the home page... it probably won't hurt if the h3 isn't a h3 on the homepage either
- The elements should probably be put inside a list whilst we are here
- This is a fun one, gap between the edge of the blue box and viewport. Doesn't seem to matter which browser and it only happens on some devices (Huawei P30 pro on browserstack)
![Screenshot_2023-08-21-12-57-10-27_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/oaknational/Oak-Web-Application/assets/102532470/96177a72-6f09-47f8-be11-da5e0fcdc403)

2023-08-22 10:29 UTC, jack-skerrett-oak approved these changes

2023-08-22 11:57 UTC, benprotheroe commented on src/node-lib/curriculum-api-2023/queries/subjectListing/subjectListing.gql
should this not be one mv? if we're doing one mv per page?

2023-08-22 12:19 UTC, k-huggs commented on src/node-lib/curriculum-api-2023/queries/subjectListing/subjectListing.gql
isn't that a scope creep for this ticket?

2023-08-22 12:49 UTC, k-huggs commented on src/node-lib/curriculum-api-2023/queries/subjectListing/subjectListing.gql
Ok, will bare that in mind for the future

2023-08-22 14:06 UTC, kimon-satan requested changes

2023-08-22 14:06 UTC, kimon-satan commented on src/node-lib/curriculum-api-2023/queries/subjectListing/subjectListing.gql
A simple workaround would be just to cut and paste the MV and rename it. Could you do that to maintain the prinicple ?

2023-08-23 08:56 UTC, benprotheroe approved these changes

2023-08-23 10:12 UTC, kimon-satan approved these changes

2023-08-23 10:23 UTC, merged

2023-08-23 10:25 UTC, oak-machine-user commented
:tada: This PR is included in version 1.225.1 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.225.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: