feat: double subject card
oaknational/Oak-Web-Application pull request #1815
Opened 2023-08-24 08:34 UTC by JBR90

## Description

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

2023-08-24 15:15 UTC, kimon-satan requested changes

2023-08-24 15:15 UTC, kimon-satan commented on src/__tests__/pages/beta/[viewType]/key-stages/[keyStageSlug]/subjects/index.test.tsx
> +import * as curriculumApi2023 from "../../../../../../../node-lib/curriculum-api-2023/__mocks__/index";
whenever you modify relative paths can you now change them to @/

2023-08-24 15:15 UTC, kimon-satan commented on src/components/SubjectCardList/SubjectCardList.stories.tsx
> +const subjects = [
Avoid type assertion  - basically it makes a nonsense of Typescript

2023-08-24 15:15 UTC, kimon-satan commented on src/components/Typography/UL.tsx
> +type ULProps = BoxProps &
I'm not sure the UL & LI  components are worthwhile as they so often end up being flexboxes in disguise. A more transparent approach is to use flexes and set the roles to "list" and "listitem" where appropriate.

2023-08-25 07:56 UTC, jack-skerrett-oak approved these changes
I'm trying my best to find issue with it, but I can't!

2023-08-25 08:56 UTC, kimon-satan approved these changes

2023-08-25 08:57 UTC, merged

2023-08-25 09:00 UTC, oak-machine-user commented
:tada: This PR is included in version 1.228.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.228.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: