Feat/lesq 253/old quiz new comp
oaknational/Oak-Web-Application pull request #1841
Opened 2023-08-30 09:54 UTC by kimon-satan

Transform the old data to match the new data schema.

Check it renders correctly for all question types

## To Test:

b) images in mcq answers

- {owa_deployment_url}/beta/teachers/programmes/maths-secondary-ks3/units/numbers-and-numerals-6c2e/lessons/mayan-numbers-c4w66d
- [[{owa_deployment_url}/beta/teachers/programmes/maths-primary-ks1/units/measure[…]to-measure-lengths-using-non-standard-units-part-2-6ngkac]({owa_deployment_url}/beta/teachers/programmes/maths-primary-ks1/units/measure%5B%E2%80%A6%5Dto-measure-lengths-using-non-standard-units-part-2-6ngkac)]({owa_deployment_url}/beta/teachers/programmes/maths-primary-ks1/units/measures-1-length-and-mass-0f65/lessons/to-measure-lengths-using-non-standard-units-part-2-6ngkac)
- **exit** [[{owa_deployment_url}/beta/teachers/programmes/science-secondary-ks3/units/ato[…]-periodic-table-9q9t0p6/lessons/chemical-reactions-p26zu7]({owa_deployment_url}/beta/teachers/programmes/science-secondary-ks3/units/ato%5B%E2%80%A6%5D-periodic-table-9q9t0p6/lessons/chemical-reactions-p26zu7)]({owa_deployment_url}/beta/teachers/programmes/science-secondary-ks3/units/atoms-and-the-periodic-table-9q9t0p6/lessons/chemical-reactions-p26zu7)

c) match questions

- **exit** {owa_deployment_url}/beta/teachers/programmes/science-secondary-ks3/units/cells-u2b1h4c/lessons/cell-structures-fxjz0y
- **starter** {owa_deployment_url}/beta/teachers/programmes/science-secondary-ks3/units/cells-u2b1h4c/lessons/diffusion-ocvf5s

d) order questions

- **starter** {owa_deployment_url}/beta/teachers/programmes/science-secondary-ks3/units/cells-u2b1h4c/lessons/cell-structures-fxjz0y
- **exit** [[{owa_deployment_url}/beta/teachers/programmes/science-secondary-ks3/units/ato[…]-9q9t0p6/lessons/development-of-the-periodic-table-r21gyc]({owa_deployment_url}/beta/teachers/programmes/science-secondary-ks3/units/ato%5B%E2%80%A6%5D-9q9t0p6/lessons/development-of-the-periodic-table-r21gyc)]({owa_deployment_url}/beta/teachers/programmes/science-secondary-ks3/units/atoms-and-the-periodic-table-9q9t0p6/lessons/development-of-the-periodic-table-r21gyc)

e. short answer questions

- **starter** [[{owa_deployment_url}/beta/teachers/programmes/science-secondary-ks3/units/ato[…]-periodic-table-9q9t0p6/lessons/chemical-reactions-p26zu7]({owa_deployment_url}/beta/teachers/programmes/science-secondary-ks3/units/ato%5B%E2%80%A6%5D-periodic-table-9q9t0p6/lessons/chemical-reactions-p26zu7)]({owa_deployment_url}/beta/teachers/programmes/science-secondary-ks3/units/atoms-and-the-periodic-table-9q9t0p6/lessons/chemical-reactions-p26zu7)
- **starter and exit** {owa_deployment_url}/beta/teachers/programmes/biology-secondary-ks4/units/cells-biology-3p8njnj/lessons/osmosis-eymw2x

f) explanatory texts

- **starter** [[{owa_deployment_url}/beta/teachers/programmes/german-secondary-ks4/units/holi[…]sing-accommodation-and-associated-problems-part-13-cmr6ct]({owa_deployment_url}/beta/teachers/programmes/german-secondary-ks4/units/holi%5B%E2%80%A6%5Dsing-accommodation-and-associated-problems-part-13-cmr6ct)]({owa_deployment_url}/beta/teachers/programmes/german-secondary-ks4/units/holidays-and-travel-9ac5/lessons/discussing-accommodation-and-associated-problems-part-13-cmr6ct)
- **exit** [[{owa_deployment_url}/beta/teachers/programmes/spanish-secondary-ks4/units/fre[…]/lessons/talking-about-what-you-usually-do-part-33-cnk32t]({owa_deployment_url}/beta/teachers/programmes/spanish-secondary-ks4/units/fre%5B%E2%80%A6%5D/lessons/talking-about-what-you-usually-do-part-33-cnk32t)]({owa_deployment_url}/beta/teachers/programmes/spanish-secondary-ks4/units/free-time-f937/lessons/talking-about-what-you-usually-do-part-33-cnk32t)

## Acceptance Criteria:

- [x]  Both quiz types render
- [x]  Question Image
- [x]  MCQ no images
- [x]  MCQ with images
- [x]  Match
- [x]  Order
- [x]  Short
- [x]  Explanatory text
- [x]  checkbox
- [x]  Unit tests

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

2023-08-30 16:01 UTC, jack-skerrett-oak requested changes
So I think the match questions are the wrong way round for the old content. Here the "choices" are displayed on the right, and the "answers" on the left, we want this the other way round (I think we have it the right way round for new quiz data)

![Screenshot 2023-08-30 at 17 00 37](https://github.com/oaknational/Oak-Web-Application/assets/102532470/fc664ec7-4b87-472c-87fd-3abb3c9478ae)

2023-08-30 16:33 UTC, kimon-satan commented on package.json
> +    "chromedriver": "^116.0.0",
yes. sorry it shouldn't have ended up in this one but it doesn't do any harm

2023-08-30 16:34 UTC, kimon-satan commented on src/node-lib/curriculum-api/transformQuizzes.ts
> +      return "explanatory-text" as keyof AnswersSchema;
I really tried but couldn't find a way . Happy to explore any ideas.

2023-08-31 09:30 UTC, kimon-satan commented
> So I think the match questions are the wrong way round for the old content. Here the "choices" are displayed on the right, and the "answers" on the left, we want this the other way round (I think we have it the right way round for new quiz data)
> 
> ![Screenshot 2023-08-30 at 17 00 37](https://user-images.githubusercontent.com/102532470/264403385-fc664ec7-4b87-472c-87fd-3abb3c9478ae.png)

Swapped now . Please check

2023-08-31 11:41 UTC, jack-skerrett-oak approved these changes

2023-08-31 11:54 UTC, merged

2023-08-31 11:57 UTC, oak-machine-user commented
:tada: This PR is included in version 1.230.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.230.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: