Feat/exemplar units header
oaknational/Oak-Web-Application pull request #1850
Opened 2023-08-31 11:22 UTC by benprotheroe

## Description

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

2023-08-31 13:48 UTC, jack-skerrett-oak requested changes
- [ ] In figma, the gap between the two boxes is 16px, it looks like you have done this but including the brush borders, so they are a bit snug
![Screenshot 2023-08-31 at 14 46 21](https://github.com/oaknational/Oak-Web-Application/assets/102532470/ee2717db-9539-4f39-9124-80d68a164561)
- [ ] The illustration isn't rendering properly
![Screenshot 2023-08-31 at 14 46 23](https://github.com/oaknational/Oak-Web-Application/assets/102532470/8f90ff1c-b806-442b-b089-a570ddd193a2)
- [ ] I didn't see this copy was also here.. could Subject Leads become subject leads? Sentence case and all that!

2023-09-01 08:14 UTC, JBR90 approved these changes
LGTM

2023-09-01 10:35 UTC, jack-skerrett-oak approved these changes

2023-09-01 10:53 UTC, merged

2023-09-01 10:56 UTC, oak-machine-user commented
:tada: This PR is included in version 1.231.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.231.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: