chore: update downloads to render icon
oaknational/Oak-Web-Application pull request #1858
Opened 2023-09-01 13:25 UTC by k-huggs

## Description

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

2023-09-01 15:21 UTC, JBR90 requested changes
Looks good, few logs to remove

2023-09-01 15:21 UTC, JBR90 commented on src/node-lib/curriculum-api-2023/queries/downloads/downloads.query.ts
> +    console.log(downloads, "<< RESULT FROM QUERY");
🔥

2023-09-01 15:21 UTC, JBR90 commented on src/pages/beta/[viewType]/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/downloads.tsx
> +  console.log(downloads, "<< from the downloads page");
🔥

2023-09-01 15:21 UTC, JBR90 commented on src/pages/beta/[viewType]/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/downloads.tsx
> +      console.log(curriculumData, "<< curriculumData");
🔥

2023-09-01 15:22 UTC, k-huggs commented on src/node-lib/curriculum-api-2023/queries/downloads/downloads.query.ts
> +    console.log(downloads, "<< RESULT FROM QUERY");
HA removed both !

2023-09-01 15:26 UTC, mantagen approved these changes

2023-09-01 15:27 UTC, mantagen commented on src/pages/beta/[viewType]/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/downloads.tsx
> +      console.log(curriculumData, "<< curriculumData");
🧯

2023-09-04 10:51 UTC, jack-skerrett-oak approved these changes
I can't see any regressions, but also with the state of downloads at the minute I am not able to see this work. Hopefully once everything is plugged in, it will work seamlessly!

2023-09-04 12:37 UTC, merged