Curric/landing page header
oaknational/Oak-Web-Application pull request #1868
Opened 2023-09-04 16:24 UTC by k-huggs

## Description

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

2023-09-05 14:02 UTC, rightsaidjames approved these changes
Looks good to me from a QA/Design perspective, pretty much pixel perfect compared to Figma. It's not yet on the Notion board, but as far as I'm concerned LGTM!

2023-09-06 13:17 UTC, andykwoods commented
blah

2023-09-06 13:20 UTC, andykwoods commented
@k-huggs Thanks for adding Screenshots for @HelenHarlow

2023-09-06 13:32 UTC, HelenHarlow commented
This may relate to a different ticket but I notice that with the lot picker component, when it is resized the button is also resized, which cuts off the copy. I think we should aim to have it so the button width stays fixed so this doesn’t happen. Other than that, all looks good to me

2023-09-06 13:32 UTC, HelenHarlow approved these changes

2023-09-06 13:45 UTC, k-huggs commented
> This may relate to a different ticket but I notice that with the lot picker component, when it is resized the button is also resized, which cuts off the copy. I think we should aim to have it so the button width stays fixed so this doesn’t happen. Other than that, all looks good to me

Noticed this, it's a regression on the button and what happens when it gets reduced in size. It'll be present across the OWA so will need to be ticketed up too

2023-09-06 14:25 UTC, mantagen requested changes
Just the formatting issue -- other than that looks good!

2023-09-06 14:25 UTC, mantagen commented on src/components/CMSImage/CMSImage.tsx
> -          originalDimensions.height,
Looks like old prettier version here... could you merge in main and locally run `npm run format` and commit the changes?

2023-09-06 15:27 UTC, mantagen approved these changes
Awesome!

2023-09-06 16:13 UTC, merged

2023-09-06 16:16 UTC, oak-machine-user commented
:tada: This PR is included in version 1.233.4 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.233.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: