ENG-391 feat(canonical lesson): spike a canonical lesson page
oaknational/Oak-Web-Application pull request #1891
Opened 2023-09-08 16:25 UTC by mantagen

[spike]

## Description

- adds a new curriculum api query
  - this calls the same MV as lesson-overview
  - it groups the same lessons together, creating a list of pathways in which the lesson is found
- adds a new page to test (currently at `/beta/teachers-2023/{lesson_slug}`

**Note:** it's a draft spike, so there's some code copy pasted from the lesson-overview query logic rather than abstracted/shared. Also haven't gone in on the page content itself yet, as there's no designs, and it's likely going to just use the same components as the lesson-overview page

2023-09-22 14:54 UTC, benprotheroe reviewed
havent we retired beta?
the link doesnt take you anywhere

2023-09-22 15:52 UTC, mantagen commented
> havent we retired beta?
> the link doesnt take you anywhere

apologies @benprotheroe , updated the description

2023-09-25 08:19 UTC, jack-skerrett-oak requested changes
Morning :) 

This is my first time looking at this canonical URL stuff so please tell me where I am wrong in my assumptions!

- This PR has made the "Download all resources button go BIG". On the currently deployed OWA this is not the case
![Screenshot 2023-09-25 at 09 00 16 (2)](https://github.com/oaknational/Oak-Web-Application/assets/102532470/8dd7209d-9512-48d4-b8f4-9b511ded4008)
- When tiers get involved, there are duplicated links
![Screenshot 2023-09-25 at 09 00 46](https://github.com/oaknational/Oak-Web-Application/assets/102532470/8d3f75b3-99a5-412d-96e1-15cc0cf3eaae)
- The unit in the image above (transverse waves) also appears in a similar set of physics units but here we only have links to the combined science units
- The transverse waves unit has a download all button when in the traditional pathway, but it doesn't here

2023-09-25 16:12 UTC, mantagen commented on src/common-lib/urls/urls.ts
> +    analyticsPageName: "Lesson Download", // @todo this should be "Lesson Download (Canonical)"?
@verityroberts @ewan-wakeman do we want to distinguish the canonical pages using the "Page name" prop? Or are we happy for it to be called "Lesson Download" regardless of whether the user is in a specific pathway?

2023-09-26 09:45 UTC, mantagen commented on src/components/Lesson/LessonAppearsIn/LessonAppearsIn.stories.tsx
> +  title: "Lesson/Lesson Appears In",
Group with other components

2023-09-26 09:46 UTC, mantagen commented on src/common-lib/urls/urls.ts
> +  programmeSlug: null;
remove these

2023-09-26 09:50 UTC, jack-skerrett-oak requested changes
Sorry, I've got more things I didn't notice :( 
- [x] Could "Lesson appears in" be changed to a H2 so that the page layout makes more sense (and then all the headings below that move up one)
- [x] The hover state is not what is shown in figma
 ![Screenshot 2023-09-26 at 10 32 58](https://github.com/oaknational/Oak-Web-Application/assets/102532470/6fedae08-bb9d-4e3c-ad4d-e0067240d999)
- [x] I don't know the full context behind these canonical URLs, but it does seem a bit odd to have something like this https://deploy-preview-1891--oak-web-application.netlify.thenational.academy/teachers/lessons/formation-of-i-l-and-t. The breadcrumb is fully visible unlike the lessons that are across multiple programmes...

2023-09-26 09:54 UTC, mantagen commented on src/components/Lesson/LessonPathwayCard/LessonPathwayCard.stories.tsx
> +//     unitSlug: string;
Remove comment

2023-09-26 09:55 UTC, mantagen commented on src/components/Lesson/lesson.helpers.test.ts
> +import { groupLessonPathways } from "./lesson.helpers"; // Replace with the actual import path
remove comment

2023-09-26 09:56 UTC, mantagen commented on src/components/Lesson/lesson.helpers.ts
> +export const getLessonOverviewBreadCumb = ({
typo

2023-09-26 09:57 UTC, mantagen commented on src/components/Lesson/lesson.helpers.ts
> +export const getLessonDownloadsBreadCumb = ({
typo

2023-09-26 10:48 UTC, mantagen commented on src/components/Lesson/lesson.types.ts
> +export type LessonBase = {
import from schema

2023-09-26 10:54 UTC, mantagen commented on src/components/SubjectIconBrushBorders/SubjectIconBrushBorders.tsx
> +  subjectSlug: string | null;
either have this optional, or optionally render this component

2023-09-26 11:12 UTC, mantagen commented on src/node-lib/curriculum-api-2023/queries/lessonOverviewCanonical/lessonOverviewCanonical.gql
> +    examboardSlug: examBoardSlug
`examBoard`

2023-09-26 11:29 UTC, kimon-satan approved these changes

2023-09-26 13:08 UTC, mantagen commented on src/common-lib/urls/urls.ts
> +    analyticsPageName: "Lesson Download", // @todo this should be "Lesson Download (Canonical)"?
For now I will leave them as is. Let me know if you want to differentiate in the tracking plan

2023-09-26 13:55 UTC, Monika-Koziol reviewed
There are a few differences between Figma and code. None of them to big to not go live with them

- [x] "Lesson appears on" should use heading 5 styling
- [ ] Top and bottom padding set to 100px
- [ ] Unit Title to be using style of Heading 6 Light
- [ ] It would be great if different exam boards tags could be different colour but if it add too much work then let's do it another time

2023-09-26 16:57 UTC, k-huggs approved these changes

2023-09-27 10:46 UTC, jack-skerrett-oak approved these changes
Lesson data is in an odd place so will make a note to test once we have a better grasp on published data

2023-09-27 11:07 UTC, merged