Feat/home page nav
oaknational/Oak-Web-Application pull request #1898
Opened 2023-09-12 15:05 UTC by benprotheroe

## Description

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

2023-09-12 15:42 UTC, njblore commented on src/components/HomePageTabImageNav/HomePageTabImageNav.stories.tsx
> +// };
can we remove this?

2023-09-12 15:42 UTC, njblore commented on src/components/HomePageTabImageNav/HomePageTabImageNav.tsx
> +import { Hr } from "../Typography";
I think we're aiming to use aliased imports everywhere instead of relative ones

2023-09-13 08:47 UTC, njblore approved these changes

2023-09-13 08:49 UTC, jack-skerrett-oak requested changes
- For some reason they have doubled up names for assistive tech (see in the green box, a very useful tab in chrome!)
![Screenshot 2023-09-13 at 09 43 51](https://github.com/oaknational/Oak-Web-Application/assets/102532470/9ca1a674-bdda-44d7-8965-9b55be3fe10b)
- When it moves to mobile width, the "new" should be removed from the curric maps
![Screenshot 2023-09-13 at 09 44 20](https://github.com/oaknational/Oak-Web-Application/assets/102532470/1b8fa16a-6c02-4078-b87d-51dfc52ebbde)
- Should these all be within a nav? Or at least within a list to show they are connected

2023-09-13 09:01 UTC, Monika-Koziol requested changes
A couple of things to check:

- [ ] after clicking on a tab the line should be black rather then yellow and black (that's a focus state for tabbing with a keyboard)
- [x] there is a small white gap between the black underline and green background
- [x] it breaks on small mobile: hide new tag, can we change font size to 14px?

2023-09-13 09:12 UTC, jack-skerrett-oak commented
> 

Not to say it should or shouldn't, but currently across the site, focus remains on an element until a user clicks away. Not sure if there is anything we can do, that is just the current state of things!

2023-09-13 12:43 UTC, Monika-Koziol reviewed
![Screenshot 2023-09-13 at 13 41 46](https://github.com/oaknational/Oak-Web-Application/assets/125288018/5907967a-102d-46c4-b1e6-49f1369cd0a6)
It still looks broken on a mobile. Am I looking at the right thing?

2023-09-13 14:06 UTC, jack-skerrett-oak requested changes
Two of my initial requests still need addressing:
- New tag doesn't disappear at narrow widths (as well as the issue Monika has shown where the icons bleed off the edge of the page, I assume everything should just get smaller once there is no space?)
- They are still just three buttons in a div. They should either be in a nav/list, or just a list. Not sure which is more applicable here.

2023-09-13 15:10 UTC, jack-skerrett-oak approved these changes

2023-09-13 15:18 UTC, Monika-Koziol approved these changes
Looking good.

2023-09-13 16:24 UTC, merged

2023-09-13 16:27 UTC, oak-machine-user commented
:tada: This PR is included in version 1.241.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.241.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: