[CUR-261] Updated 'intent' to 'explainer' on overview page
oaknational/Oak-Web-Application pull request #1914
Opened 2023-09-19 16:14 UTC by sonalisin

## Description

- Updated the title of curriculum intent to curriculum explainer
- Updated font sizes for all headings across overview tab and curriculum header

## How to test

1. Go to {owa_deployment_url}
2. Go to any subject/phase combination
3. You should see 'Curriculum explainer' instead of 'Curriculum intent'

## Screenshots

How it used to look (delete if n/a):
![Screenshot 2023-09-19 at 17 14 03](https://github.com/oaknational/Oak-Web-Application/assets/32605982/7f36993f-e517-4ff0-97d9-1ca76d0ceabe)

How it should now look:
![Screenshot 2023-09-19 at 17 13 37](https://github.com/oaknational/Oak-Web-Application/assets/32605982/5e24b547-12c0-4404-a040-0fc353f03725)

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

2023-09-19 16:15 UTC, k-huggs approved these changes

2023-09-20 09:35 UTC, rightsaidjames requested changes
Looks much better! But the line height for the H2 headings should be 48px not 40px.

Also there's not enough spacing between the headings and the paragraphs below them - currently it's a bit too tight, especially in the Curriculum partner component.

![Screenshot 2023-09-20 at 10 26 12](https://github.com/oaknational/Oak-Web-Application/assets/3018395/edba478a-a70f-4494-b35a-8f3d16165d51)

2023-09-20 10:29 UTC, lioneljingles approved these changes
Looks good

2023-09-21 08:48 UTC, merged

2023-09-21 08:51 UTC, oak-machine-user commented
:tada: This PR is included in version 1.247.3 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.247.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: