LESQ-266 feat(homepage): homepage banner
oaknational/Oak-Web-Application pull request #1949
Opened 2023-09-28 15:33 UTC by benprotheroe

## Description

create homepage banner
add banner to teachers homepage

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

2023-09-28 16:01 UTC, Monika-Koziol requested changes
A couple of changes:

- [ ] Can the content be full width so it aligns with the top nav
- [ ]  Padding all round set to 24px
- [ ] Mobile has a different view with button only
- [ ] Top green line should be thicker by 3 more pixels

2023-09-29 08:23 UTC, njblore requested changes
Just left a question on the component structure, otherwise looks good

2023-09-29 08:23 UTC, njblore commented on src/pages/teachers/index.tsx
> +      <HomePageBanner />
should this live in the `AppHeader`? seems a bit strange just floating above `AppLayout`

2023-09-29 08:39 UTC, jack-skerrett-oak approved these changes
I have nothing to add outside of Monika and Tash's points (see here that at least from an a11y standpoint all code should be within "accessibility landmarks" https://www.w3schools.com/accessibility/accessibility_landmarks.php)

2023-09-29 10:32 UTC, Monika-Koziol requested changes
Sorry one last small change. Looking at it I still think it's still quite tall. 

- [ ] set top and bottom padding to 16px so it's the same on mobile and desktop and all the way round

2023-09-29 10:39 UTC, njblore approved these changes

2023-09-29 11:06 UTC, Monika-Koziol approved these changes
Looking good

2023-09-29 12:49 UTC, merged