Fix/lesq 377/homepage tab
oaknational/Oak-Web-Application pull request #1998
Opened 2023-10-10 13:09 UTC by kimon-satan

## Description

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2023-10-10 13:40 UTC, njblore requested changes

2023-10-10 13:40 UTC, njblore commented on src/components/NewButtons/HomepageTabImageButton/HomePageTabImageButton.test.tsx
> +  it("renders active image when isCurrent is false", () => {
this should be 'renders passive image' right?

2023-10-10 13:40 UTC, njblore commented on src/components/NewButtons/HomepageTabImageButton/HomePageTabImageButton.test.tsx
> +import renderWithTheme from "../../../__tests__/__helpers__/renderWithTheme";
missed this import

2023-10-10 13:59 UTC, jack-skerrett-oak approved these changes

2023-10-10 17:38 UTC, njblore approved these changes

2023-10-11 08:20 UTC, merged

2023-10-11 08:22 UTC, oak-machine-user commented
:tada: This PR is included in version 1.274.2 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.274.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: