chore: dl-card component and story
oaknational/Oak-Web-Application pull request #2045
Opened 2023-10-24 17:49 UTC by k-huggs

## Description

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2023-10-25 12:43 UTC, njblore requested changes
looks good just a couple of comments!

2023-10-25 12:43 UTC, njblore commented on src/components/DownloadComponents/DLCard/DLCard.tsx
> +  /* cursor: pointer; */
👁️

2023-10-25 12:43 UTC, njblore commented on src/components/DownloadComponents/DLCard/DLCard.tsx
> +            error message
should this be the actual error? it also seems to be sitting within the card at the mo 
<img width="352" alt="Screenshot 2023-10-25 at 13 35 45" src="https://github.com/oaknational/Oak-Web-Application/assets/45038878/f49d3a41-706a-4350-b845-eb9488357cff">

2023-10-25 13:28 UTC, Monika-Koziol requested changes
@k-huggs  looking good a few little tweaks
- [x] Hover state: the white should change to grey 20 f2f2f2
- [x]  The second line of text: currently it forces sentence case. Can it be just any input? We might sometimes have all caps in there.
- [ ] If someone enters a very long text could it truncate in the top line? 
More of the question but how are the icons managed? I wasn’t able to change them

2023-10-25 14:08 UTC, k-huggs commented
> @k-huggs looking good a few little tweaks
> 
> * [x]  Hover state: the white should change to grey 20 f2f2f2
> * [ ]   The second line of text: currently it forces sentence case. Can it be just any input? We might sometimes have all caps in there.
> * [ ]  If someone enters a very long text could it truncate in the top line?
>   More of the question but how are the icons managed? I wasn’t able to change them

1. Changed the hover state ✅
2. Think it would be better to keep them all the same either capital case or capitalised
3. The longest text possible is 'Additional material' for these cards as they need to be a selected from a resource type

Try the following to change images in the resource type
"intro-quiz-questions", "intro-quiz-answers", "exit-quiz-questions", "exit-quiz-answers", "worksheet-pdf", "worksheet-pptx", "supplementary-pdf", "supplementary-docx"

2023-10-25 15:34 UTC, Monika-Koziol commented
@k-huggs looking good from my side.

2023-10-25 15:50 UTC, njblore approved these changes

2023-10-26 08:48 UTC, Monika-Koziol approved these changes

2023-10-26 13:40 UTC, merged

2023-10-26 13:43 UTC, oak-machine-user commented
:tada: This PR is included in version 1.289.1 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.289.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: