Feat/downloads confirmation state
oaknational/Oak-Web-Application pull request #2068
Opened 2023-11-01 17:53 UTC by k-huggs

## Description

- Creates download confirmation component
- 

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2023-11-02 15:20 UTC, njblore reviewed
looks good just a few comments, not blocking

2023-11-02 15:20 UTC, njblore commented on src/components/DownloadComponents/DownloadConfirmation/DownloadConfirmation.tsx
> +        <Box>
what's this box for?

2023-11-02 15:20 UTC, njblore commented on src/components/DownloadComponents/DownloadConfirmation/DownloadConfirmation.tsx
> +        <Box $maxWidth={600}>
can this be a flex with a gap instead of adding margin to the header?

2023-11-02 15:20 UTC, njblore commented on src/components/Lesson/LessonDownloads/LessonDownloads.page.tsx
> +    useState<boolean>(false);
now we have a few states this page could be in it might be better to combine them into one, eg `uiState = 'default' | 'downloading' | 'succeeded'` ?

2023-11-02 15:30 UTC, jack-skerrett-oak requested changes
- We will probably want to make that "thanks for downloading" a H1, there isn't one on the page
- The chevron looks a tiny bit smaller than the figma, not the end of the world for me, just thought I would point it out (24px vs 20px)
- Edge case, and it might need to be brought to the table for a chat unless it is clear what needs to happen. If you are on a canonical lesson page for a lesson that exists in multiple units/programmes (https://deploy-preview-2068--oak-web-application.netlify.thenational.academy/teachers/lessons/accuracy-of-final-answers/downloads?preselected=all) and then download an asset, you do not get the thanks! page

2023-11-02 15:57 UTC, jack-skerrett-oak requested changes
Haven't seen something like this in a while
- The svgs (big tick thing, focus outline and chevron) aren't loading on Safari
    - I have dug a bit deeper and it seems to be fine on the new OS (Sonoma), but on the previous one that I haven't yet updated to (Ventura) I am seeing this issue
   
<img width="985" alt="Screenshot 2023-11-02 at 15 38 42" src="https://github.com/oaknational/Oak-Web-Application/assets/102532470/79e8e4cd-52b2-4c0c-9af0-b63e9cc8e6c7">

2023-11-02 16:01 UTC, k-huggs commented on src/components/DownloadComponents/DownloadConfirmation/DownloadConfirmation.tsx
> +        <Box>
Removed ✅

2023-11-02 16:01 UTC, k-huggs commented
> * We will probably want to make that "thanks for downloading" a H1, there isn't one on the page
> * The chevron looks a tiny bit smaller than the figma, not the end of the world for me, just thought I would point it out (24px vs 20px)
> * Edge case, and it might need to be brought to the table for a chat unless it is clear what needs to happen. If you are on a canonical lesson page for a lesson that exists in multiple units/programmes (https://deploy-preview-2068--oak-web-application.netlify.thenational.academy/teachers/lessons/accuracy-of-final-answers/downloads?preselected=all) and then download an asset, you do not get the thanks! page

- H1 ✅
- Canonical lesson ✅
- This should be the smallest button variant

2023-11-02 16:14 UTC, njblore approved these changes

2023-11-03 10:44 UTC, k-huggs commented
> Haven't seen something like this in a while
> 
> * The svgs (big tick thing, focus outline and chevron) aren't loading on Safari
>   
>   * I have dug a bit deeper and it seems to be fine on the new OS (Sonoma), but on the previous one that I haven't yet updated to (Ventura) I am seeing this issue
> 
> <img alt="Screenshot 2023-11-02 at 15 38 42" width="985" src="https://user-images.githubusercontent.com/102532470/280051768-79e8e4cd-52b2-4c0c-9af0-b63e9cc8e6c7.png">

Should now be rendering on Safari Ventura
<img width="1366" alt="Screenshot 2023-11-03 at 10 44 02" src="https://github.com/oaknational/Oak-Web-Application/assets/91190841/07ca4ae9-2691-47d3-bf63-b98671a86b87">

2023-11-06 09:15 UTC, jack-skerrett-oak approved these changes

2023-11-07 17:39 UTC, merged

2023-11-07 17:42 UTC, oak-machine-user commented
:tada: This PR is included in version 1.295.6 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.295.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: