Feat/downloads confirmation container
oaknational/Oak-Web-Application pull request #2080
Opened 2023-11-08 07:57 UTC by k-huggs

## Description

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2023-11-09 11:08 UTC, njblore requested changes

2023-11-09 11:08 UTC, njblore commented on src/components/DownloadComponents/NextLessonContainer/NextLessonContainer.tsx
> +          {nextLessons.map((lesson: NextLesson, i: number) => {
might be a bit cleaner to just `nextLessons.slice(0,2).map....` then you don't need the if and null return?

2023-11-09 11:08 UTC, njblore commented on src/node-lib/curriculum-api-2023/queries/lessonDownloads/lessonDownloads.schema.ts
> +});
just curious why this change is needed?

2023-11-09 11:08 UTC, njblore commented on src/components/DownloadComponents/NextLessonContainer/NextLessonContainer.tsx
> +          {nextLessons.map((lesson: NextLesson, i: number) => {
actually just checked and the method used to get next lessons already limits to 3 (`getNextLessonsInUnit`)! so this may not be necessary at all

2023-11-09 11:08 UTC, njblore commented on src/components/DownloadComponents/DownloadConfirmation/DownloadConfirmation.tsx
> +  nextLessons?: NextLesson[];
I'm not sure this is optional as the query method returns an empty array if there are no next lessons - possibly the canonical page is different?

2023-11-09 16:12 UTC, rightsaidjames reviewed
Not sure what @Monika-Koziol thinks of this, but there seems to be a lot of variability and a lack of even-ness in the gutter sizes on mobile and tablet. Should they be proportionally consistent within each breakpoint?

<img width="524" alt="Screenshot 2023-11-09 at 15 17 09" src="https://github.com/oaknational/Oak-Web-Application/assets/3018395/282c6db1-4835-47ea-af7c-9c6a7209f33b">
<img width="439" alt="Screenshot 2023-11-09 at 15 17 52" src="https://github.com/oaknational/Oak-Web-Application/assets/3018395/c2025efa-59c2-42ff-b738-0514e5083e39">
<img width="503" alt="Screenshot 2023-11-09 at 15 18 15" src="https://github.com/oaknational/Oak-Web-Application/assets/3018395/bc4f3c82-2911-4c21-a89e-ec1738ce8c5c">
<img width="834" alt="Screenshot 2023-11-09 at 15 18 41" src="https://github.com/oaknational/Oak-Web-Application/assets/3018395/945759f2-ab29-4146-95f5-d2a71731fdfe">
<img width="876" alt="Screenshot 2023-11-09 at 15 18 50" src="https://github.com/oaknational/Oak-Web-Application/assets/3018395/31aa7898-6dfc-492b-9d72-f68865440778">

2023-11-09 17:56 UTC, k-huggs commented
> Not sure what @Monika-Koziol thinks of this, but there seems to be a lot of variability and a lack of even-ness in the gutter sizes on mobile and tablet. Should they be proportionally consistent within each breakpoint?
> 
> <img alt="Screenshot 2023-11-09 at 15 17 09" width="524" src="https://user-images.githubusercontent.com/3018395/281795665-282c6db1-4835-47ea-af7c-9c6a7209f33b.png"> <img alt="Screenshot 2023-11-09 at 15 17 52" width="439" src="https://user-images.githubusercontent.com/3018395/281795670-c2025efa-59c2-42ff-b738-0514e5083e39.png"> <img alt="Screenshot 2023-11-09 at 15 18 15" width="503" src="https://user-images.githubusercontent.com/3018395/281795672-bc4f3c82-2911-4c21-a89e-ec1738ce8c5c.png"> <img alt="Screenshot 2023-11-09 at 15 18 41" width="834" src="https://user-images.githubusercontent.com/3018395/281795673-945759f2-ab29-4146-95f5-d2a71731fdfe.png"> <img alt="Screenshot 2023-11-09 at 15 18 50" width="876" src="https://user-images.githubusercontent.com/3018395/281795675-31aa7898-6dfc-492b-9d72-f68865440778.png">

These should be fixed now

2023-11-10 09:49 UTC, jack-skerrett-oak requested changes
- I cannot download from this lesson (https://deploy-preview-2080--oak-web-application.netlify.thenational.academy/teachers/programmes/english-secondary-ks4-edexcel/units/macbeth-and-masculinity-the-struggle-for-power/lessons/writing-nuanced-responses-about-the-role-of-masculinity-in-macbeth/downloads?preselected=all). I am not sure why, I thought it was because it is the last lesson in the unit, but that rule doesn't apply else where across the new content (this lesson can be downloaded on the live site)
- I am sure we wrote the acceptance criteria somewhere, but the tickets seem to have changed. When you only have 1 or 2 lessons, the component should stay the same size, justified to the left,  rather than taking up more space than usual when only 1 or 2 next lessons are shown (unless this spec has changed, in which case, ignore me)
![Screenshot 2023-11-10 at 09 38 47](https://github.com/oaknational/Oak-Web-Application/assets/102532470/c69c024b-2d21-4f8c-89f4-84282faae935)
- The spacing issue raised by James still seems to be present (space between the boxes seems to be 16px, 12px, 8px on desktop, tablet, mobile respectively, they are all 16px in the designs)

2023-11-10 11:03 UTC, Monika-Koziol approved these changes
@k-huggs looking good. Also, adding he note that we reviewed the solution for one extra lesson to take and accepted it looks a bit wide on tablet and desktop.

2023-11-10 12:14 UTC, njblore commented on src/components/DownloadComponents/DownloadConfirmation/DownloadConfirmation.tsx
> +  nextLessons?: NextLesson[];
confirmed that canonical downloads page does not include next lessons

2023-11-10 12:14 UTC, njblore approved these changes

2023-11-10 12:26 UTC, jack-skerrett-oak approved these changes
Mystery lesson not downloading seems to be a staging issue.

2023-11-13 08:33 UTC, merged

2023-11-13 08:35 UTC, oak-machine-user commented
:tada: This PR is included in version 1.300.2 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.300.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: