fix: new search api hits with no legacy suffix - LESQ-427
oaknational/Oak-Web-Application pull request #2104
Opened 2023-11-21 11:12 UTC by JBR90

## Description

Music year: 1973

- Only adds legacy prefix to legacy lesson and unit search hits 
- Adds legacy flag to each hit from fetch results 2020 and 2023
- Adds tests

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-2104--oak-web-application.netlify.thenational.academy
Go to search and use flag=enable_2023_search_api 

The links should work for new lessons and units
https://deploy-preview-2104--oak-web-application.netlify.thenational.academy/teachers/search?term=Measuring+waves&flag=enable_2023_search_api

and still work for old
https://deploy-preview-2104--oak-web-application.netlify.thenational.academy/teachers/programmes/computing-secondary-ks4-l/units/programming-2-selection-cbc4/lessons

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2023-11-21 17:04 UTC, jack-skerrett-oak requested changes
I was just about to approve and then found an issue with a Maths unit :D If you search for units called "Surds", the unit "Surds" is returned as one of the new units. This is one of the new units, however it is being assigned a legacy slug so you cannot navigate to the unit page. Not sure if it is because the programme slug matches the old maths programme slugs (other than the -l of course)?

https://deploy-preview-2106--oak-web-application.netlify.thenational.academy/teachers/search?term=surds&contentTypes=unit&flag=enable_2023_search_api

2023-11-22 09:11 UTC, JBR90 commented
> I was just about to approve and then found an issue with a Maths unit :D If you search for units called "Surds", the unit "Surds" is returned as one of the new units. This is one of the new units, however it is being assigned a legacy slug so you cannot navigate to the unit page. Not sure if it is because the programme slug matches the old maths programme slugs (other than the -l of course)?
> 
> https://deploy-preview-2106--oak-web-application.netlify.thenational.academy/teachers/search?term=surds&contentTypes=unit&flag=enable_2023_search_api

Good spot Jack! Looks like it was React getting confused with list items with the same key, should be sorted with the next commit.

2023-11-22 10:28 UTC, jack-skerrett-oak approved these changes

2023-11-22 11:00 UTC, njblore approved these changes

2023-11-22 15:00 UTC, merged

2023-11-22 15:02 UTC, oak-machine-user commented
:tada: This PR is included in version 1.305.3 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.305.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: