Feat/new search hit card - LESQ-459
oaknational/Oak-Web-Application pull request #2114
Opened 2023-11-28 12:16 UTC by JBR90

## Description

Music year: {owa_music_year}

## Acceptance Criteria:

- [x]  New component for search
- [x]  New component shows all details on result (type, key stage, exam boards etc) (no exam or year data yet - LESQ-486)
- [x]  Lesson is pink circle, unit is blue square
- [x]  Units just have title, lessons have title and description
- [x]  See lesson/see unit button
- [x]  Whole thing clickable (for now)
- [x]  Lesson metadata component should be able to handle multiple exam boards
- [x]  search results page is using this new card

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2023-11-28 13:59 UTC, jack-skerrett-oak requested changes
- I confused myself checking on the designs because everything is labelled "Lesson", but I think currently the lesson/unit cards are the wrong way round. In our browse journey, units are blue and lessons are pink. 
- The "see lesson" links are lacking the focus styling they have in figma`

I will continue reviewing after this meeting!

2023-11-28 14:00 UTC, Monika-Koziol requested changes
Coming along really well. A few small changes if possible:

- [x] Use grey-60 for the meta content (lesson, key stage, etc,)
- [ ] There is a bigger gap between card component and filters. In figma I left one column width. Or the card can have a max-width 734px?

2023-11-28 16:45 UTC, Monika-Koziol reviewed
Looking great. Not sure if this is part of this ticket but now the new search bar got merged would it be possible for the `search bar+button` to be the same width as the search results card?

2023-11-29 07:49 UTC, k-huggs commented on src/components/SearchResultsItem/SearchResultsItem.test.tsx
> +      expect(searchResultClicked).toHaveBeenCalled();
Is it worth testing what this should be called with at the same time?

2023-11-29 07:59 UTC, k-huggs approved these changes
One small comment on testing, but LGTM ✅

2023-11-29 08:48 UTC, jack-skerrett-oak approved these changes
Looks great. I like what you have done with the area labels on the search results :)

2023-11-29 08:52 UTC, jack-skerrett-oak requested changes
Actually I have just noticed something on iPhone on browser stack. The bullet between the type and key stage gets very squished 
![Screenshot 2023-11-29 at 08 51 19](https://github.com/oaknational/Oak-Web-Application/assets/102532470/e4ac2f83-abf8-431d-ac55-3dd26d95c124)

2023-11-29 10:44 UTC, jack-skerrett-oak approved these changes
OK, that might have just been a browser stack issue

2023-11-29 11:00 UTC, merged

2023-11-29 11:03 UTC, oak-machine-user commented
:tada: This PR is included in version 1.308.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.308.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: