chore: update avo events
oaknational/Oak-Web-Application pull request #2145
Opened 2024-01-03 12:04 UTC by k-huggs

## Description

Music year: {owa_music_year}

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-01-03 13:09 UTC, JBR90 reviewed
Looks good - only this is the 'only' in the tests and 
 `Analytics Use Case` = null from home page search - is this expected ? 



<br class="Apple-interchange-newline">

2024-01-03 14:24 UTC, k-huggs commented
> Looks good - only this is the 'only' in the tests and `Analytics Use Case` = null from home page search - is this expected ?

Fixed the .only - I think this may be because the URL is /#teachers this was pre-exisiting behaviour should I add it to the ticket?

2024-01-03 14:58 UTC, JBR90 approved these changes

2024-01-04 12:01 UTC, jack-skerrett-oak requested changes
- "Search journey initiated" doesn't seem to be (always) sent when the search box is selected. 
- "Search journey initiated" has a depth of "refine", I can't confirm if that is right or wrong but I feel it should be "interest"?
- I don't know how Ewan intends for "context" to work, but currently if you search from the homepage, the resulting "Search Results Displayed" event has a context of "search" which kind of makes sense because that is where the search results are displayed, but we then lose that those search results were displayed as a result of a search from the homepage... possibly one for Ewan.
- If you click on a unit result, then in the "Search result opened" event, it populates the "Lesson name" as whatever the unit name is. I imagine this should be null along with the "lesson slug"
- If you click a lesson result, then in the "Search result opened" event, it populates the "Unit name" with whatever the lesson name is. Kind of the inverse of the above, but we have a unit name that we should be using. "Unit slug" is fine!

Only key stage filters returned in the "Search Filter Option Selected", I assume that will be fixed on the exam board filter branch, as well as the introduction of the "Search Refined" event.

"Search result expanded" not included on this branch.

2024-01-04 13:18 UTC, njblore commented on src/components/HomePageTabs/OldBetaHomeTab/OldBetaHomeTab.tsx
>      });
is this component in use anymore? I don't see it being used anywhere

2024-01-04 14:27 UTC, k-huggs commented
> * earch journey initiated" has a depth of "refine", I can't confirm if that is right or wrong but I feel it should be "interest"?

- Removed the depth field as we're going to do more work on defining it
- Search journey is initiated after entering some text, not just on selection of the search box
- Unit and Lesson slug bugs should be fixed
- Filters will be added on the examboard PR
- Search results expanded will be on Joe's PR

2024-01-04 16:29 UTC, jack-skerrett-oak requested changes
Still looks like unit name is not reported when opening a lesson result
![Screenshot 2024-01-04 at 16 22 46](https://github.com/oaknational/Oak-Web-Application/assets/102532470/9252fed9-0275-4c8b-b8b0-c0fc56d4d753)

2024-01-04 16:39 UTC, jack-skerrett-oak approved these changes
Kyle has said we do not have access to the unit name at this point, so happy to dismiss my previous review comment

2024-01-05 11:34 UTC, merged

2024-01-05 11:36 UTC, oak-machine-user commented
:tada: This PR is included in version 1.315.1 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.315.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: