Feat/lesq 153/html lists a11y [LESQ-153]
oaknational/Oak-Web-Application pull request #2146
Opened 2024-01-04 09:42 UTC by njblore

## Description

Music year: {owa_music_year}

- Created a `GridList` and `GridAreaListItem` components to make semantic lists in grids possible
- Refactored the `LessonElementLinks` on the plan a lesson page to make it easier to work with in a list
- Refactored the bio modal layout so it's all in a single list instead of nested
- Wrapped other elements in `ul`, `ol` and `li` where appropriate

## How to test

Use the inspector to view the elements on the page

1. Go to {owa_deployment_url}/lesson-planning
2. You should see the icons at the top of the page are in a list, as well as the numbered list below (ACs 1 & 2)
4. Go to {owa_deployment_url}/about-us/leadership and {owa_deployment_url}/about-us/board
5. You should see the links in the header are in a list (AC 3) and the bio cards below are in a list (AC 4) as well as the documents on the /board page (AC 5)
6. Go to {owa_deployment_url}/about-us/partners
7. You should see the logos are in a list (AC 6)
8. Go to {owa_deployment_url}/teachers/key-stages/ks1/subjects
9. You should see the subject cards are in a list (AC 7)

It should otherwise look the same

## ACs
1. Plan a lesson link section (the circle link icons to different lesson components) should be a list of links
2.  Plan a lesson, the “1. Find the right lesson, 2. Tailor…” looks as though it should be a list, but in HTML it is a bunch of divs
3.  About us link section (who we are, leadership etc) should be a list of links
4.  List of board/leadership cards in about us should be lists
5.  Documents on the about-us/board page should be a list
6.  List of partner logos on about-us/partners should be a list
7.  List of subjects on a subject listing page

2024-01-04 14:55 UTC, jack-skerrett-oak requested changes
- The numbered section on plan a lesson should be ol rather than ul
- There is some phantom member of the leadership team hanging over Matt's shoulder
![Screenshot 2024-01-04 at 14 01 27](https://github.com/oaknational/Oak-Web-Application/assets/102532470/f38ec502-5f35-4eb8-98ef-ee1319cf1a98)

2024-01-05 09:46 UTC, jack-skerrett-oak approved these changes

2024-01-05 10:39 UTC, JBR90 approved these changes

2024-01-05 10:41 UTC, merged

2024-01-05 10:43 UTC, oak-machine-user commented
:tada: This PR is included in version 1.314.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.314.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: