chore: initial commit for specialist view
oaknational/Oak-Web-Application pull request #2187
Opened 2024-01-15 14:26 UTC by k-huggs

## Description

Music year: {owa_music_year}

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-01-16 09:46 UTC, njblore commented on src/pages/teachers/programmes/[programmeSlug]/units.tsx
> +    if (!isSpecialistUnit(props)) {
specialist pages will be in a different folder/route (`specialistProgrammes/[programmeSlug]/specialistUnits`) so this page shouldn't need to worry about there being any specialist data

2024-01-16 09:50 UTC, njblore commented on src/components/UnitAndLessonLists/ListItemHeader.tsx
> +    yearTitle?: string | null;
specialist doesn't have years or exemplar status

2024-01-16 09:51 UTC, njblore commented on src/components/OptionalityCard/OptionalityCard.tsx
> +  unitOptions: UnitOption[] | SpecialistUnit;
specialist won't have optionality right?

2024-01-16 09:52 UTC, njblore commented on src/components/TeacherViews/SpecialistUnitListing/SpecialistUnitListing.view.tsx
> +  developmentalStageSlug: string;
I think developmentalStage needs to be optional (therapies have none, possibly not all specialist does)

2024-01-17 12:43 UTC, JBR90 commented on src/components/TeacherComponents/UnitList/UnitList.tsx
> +                {item.length > 1 && isUnitOption(item) ? (
Do some specialist items have more than one pathway at this point?

2024-01-17 12:47 UTC, JBR90 approved these changes
Approved with question

2024-01-17 14:16 UTC, jack-skerrett-oak requested changes
- [x] The subject name is missing in the breadcrumb, at this point is should be displayed (and not clickable)
- [ ] When at tablet widths, the programme options stack on top of each other. In Nirav's design they go side by side, and I assume, scrollable (at the minute if you squash down Maths enough, the options bleed off the edge of the page badly https://www.thenational.academy/teachers/programmes/maths-secondary-ks4-foundation-l/units)

2024-01-17 15:48 UTC, jack-skerrett-oak approved these changes
We have made this ticket to cover the work needed to add in a scrollable component at mobile widths https://www.notion.so/oaknationalacademy/I-want-a-horizontal-scroll-for-when-programme-names-become-to-long-on-the-subject-listing-page-4fa923916f2e4261899b718760310fc9?pvs=4

2024-01-17 15:57 UTC, merged

2024-01-17 15:59 UTC, oak-machine-user commented
:tada: This PR is included in version 1.327.1 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.327.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: