fix: remove margin from subject card [LESQ-625]
oaknational/Oak-Web-Application pull request #2257
Opened 2024-02-15 13:55 UTC by njblore

## Description

Music year: {owa_music_year}

- remove padding on subject listing cards so full PSED title fits

## How to test

1. Go to {owa_deployment_url}
2. Should look the same

## Screenshots
<img width=400 src="https://github.com/oaknational/Oak-Web-Application/assets/45038878/fdf22bc5-910b-4ed7-ab0d-29efb4bef606">

How it should now look:
<img width=400 src="https://github.com/oaknational/Oak-Web-Application/assets/45038878/0686053c-a262-45f5-9d3e-59fa9ba76362">

## Checklist

2024-02-15 16:29 UTC, Monika-Koziol requested changes
I'd say the better way to fix it would be to drop the heading size to 20px, which would give titles more breathing space. And it would work for all of the subjects. 

Also not part of this ticket but the subtext under areas of learning has too many words per line. Can we limit to half a page on desktop only?

2024-02-16 08:49 UTC, njblore commented
thanks @Monika-Koziol I've made that change to the font size, and made a ticket for the subheading width

2024-02-16 10:30 UTC, Monika-Koziol approved these changes

2024-02-16 11:47 UTC, merged

2024-02-16 11:49 UTC, oak-machine-user commented
:tada: This PR is included in version 1.356.1 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.356.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: