LESQ-693 -  Refactor: share link to pupil experience by subject
oaknational/Oak-Web-Application pull request #2304
Opened 2024-03-08 15:58 UTC by k-huggs

## Description

Music year: {owa_music_year}

- Amends how links are generated to be done by subject 

## Issue(s)

Fixes #LESQ-693

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-03-11 09:01 UTC, njblore requested changes

2024-03-11 09:01 UTC, njblore commented on src/components/TeacherViews/LessonShare/LessonShare.view.tsx
>  // Temporary - list of lessons live on pupil experience for sharing
these comments just need updating to say subjects now

2024-03-11 09:12 UTC, njblore approved these changes

2024-03-11 09:57 UTC, jack-skerrett-oak requested changes
I didn't check the ticket before it got worked on! 

We are also going to need to extend this to the weird, psuedo-english subjects in KS2 (english grammar, english reading for pleasure, english spelling)

I need to pop into a meeting but will continue having a look after!

2024-03-11 10:09 UTC, k-huggs commented
> I didn't check the ticket before it got worked on!
> 
> We are also going to need to extend this to the weird, psuedo-english subjects in KS2 (english grammar, english reading for pleasure, english spelling)
> 
> I need to pop into a meeting but will continue having a look after!

Added ✅

2024-03-11 16:39 UTC, rightsaidjames commented
I'm waiting to hear back from @aakeshp on the priority of this, but me and @jack-skerrett-oak have discovered a small flaw in the current share URL generation logic that affects the 'weird, psuedo-english subjects in KS2'.

This share page from the English Spelling programme:
https://deploy-preview-2304--oak-web-application.netlify.thenational.academy/teachers/programmes/english-spelling-primary-ks2-l/units/silent-letters-3eb2/lessons/to-investigate-silent-letters-c9gk4r/share?preselected=all 

... links out to:

 https://thenational.academy/pupils/lessons/to-investigate-silent-letters-c9gk4r?share=true
 
 .... but this lesson's 'View all lessons' link points to https://classroom.thenational.academy/units/the-day-the-crayons-quit-persuasive-writing-0c4a because the lesson exists in both units.
 
If the share URL was:
https://www.thenational.academy/pupils/l/silent-letters-3eb2/lessons/to-investigate-silent-letters-c9gk4r?share=true (i.e. it included the `/l/` prefix followed by the unit slug and another `/`)

.... then the 'View all lessons' link correctly points to:
 https://classroom.thenational.academy/units/silent-letters-3eb2
 
 So... @k-huggs / @njblore I think we need to fix this by adopting the same URL structure that's used in classroom.thenational.academy for all pupil experience share links:
 
` /pupils/l/[unitSlug]/lessons/[lessonSlug]`

You can see this in action here:
https://classroom.thenational.academy/units/the-canterbury-tales-the-knights-tale-chaucer-e7e8

And here's the Acorn code that enables it:
https://github.com/oaknational/Acorn/pull/770/files#diff-7c30b00d23f898eb7147c7db64e229215da2171ee958161c636620a1e1765e0eR156

Is this fix doable, and if so is this something that @simonh-oak and/or @benprotheroe could help with?

2024-03-12 13:36 UTC, jack-skerrett-oak approved these changes

2024-03-12 13:37 UTC, jack-skerrett-oak reviewed
Should have said in that approval, we are not requiring any more changes on this PR. We have created a ticket to address the issue of lessons in multiple units here: https://www.notion.so/oaknationalacademy/Sharing-lessons-to-pupils-should-not-direct-them-to-canonical-pupil-pages-5b1560b32b5f46b39aaf3277738f1ae8?pvs=4

2024-03-12 14:09 UTC, merged