LESQ-517: Add specialist to the hamburger menu
oaknational/Oak-Web-Application pull request #2325
Opened 2024-03-20 16:49 UTC by k-huggs

## Description

Music year: {owa_music_year}

- Adds link to Specialist to the the hamburger menu

## Issue(s)

Fixes #LESQ-517

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-03-26 09:05 UTC, njblore approved these changes

2024-03-26 09:21 UTC, jack-skerrett-oak requested changes
The ticket is poorly written, but there is a comment on the ticket that asks stuff to be added to the footer. 
"– add EYFS
– add Specialist 
– and remove Teacher Hub? "
I think all we need to do from that ticket is add specialist to the footer, just below EYFS I think will be fine!

2024-03-26 10:24 UTC, k-huggs commented
> The ticket is poorly written, but there is a comment on the ticket that asks stuff to be added to the footer. "– add EYFS – add Specialist – and remove Teacher Hub? " I think all we need to do from that ticket is add specialist to the footer, just below EYFS I think will be fine!

So just to confirm, add Specialist needs to be added to the footer

2024-03-27 14:44 UTC, jack-skerrett-oak approved these changes

2024-03-27 15:04 UTC, merged