Feat/lesq 722/specialist canonical pages [LESQ-722]
oaknational/Oak-Web-Application pull request #2339
Opened 2024-03-28 09:16 UTC by njblore

## Description

Music year: {owa_music_year}

- add a canonical specialist lesson query
- update canonical lesson page to use this query
- remove 'lesson appears in' from canonical page due to complexity of types - will add another ticket to add this back in

## How to test

1. Go to {owa_deployment_url}/teachers/lessons/sensory-story-a-christmas-carol-cgvk0t
3. You should see the canonical lesson page for specialist

2024-03-28 11:24 UTC, jack-skerrett-oak requested changes
- The links to download/share individual resources takes the user to a canonical share/download page which doesn't exist

2024-03-28 11:37 UTC, k-huggs approved these changes

2024-04-02 10:51 UTC, jack-skerrett-oak approved these changes
I've spotted another bug but it is unrelated to canonical specialist so I will make another ticket https://www.notion.so/oaknationalacademy/Clicking-Back-to-lesson-after-a-successful-download-404s-for-specialist-6be77c1f78c1479b99c377ad725c17a8?pvs=4

2024-04-02 10:54 UTC, merged

2024-04-02 10:56 UTC, oak-machine-user commented
:tada: This PR is included in version 1.397.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.397.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: