Refactor/subject listing use new api
oaknational/Oak-Web-Application pull request #2347
Opened 2024-04-03 15:27 UTC by JBR90

## Description

Music year: {owa_music_year}

-remove query to legacy api on subject listing page
-update tests to use the 2023 schema fixture
move lesson overview schema def to 2023 api

How to test
Go to https://deploy-preview-2344--oak-web-application.netlify.thenational.academy/
Click on subject listing page for different keystages
You should see everything working as expected

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-04-04 08:58 UTC, JBR90 commented on src/pages/teachers/key-stages/[keyStageSlug]/subjects/index.tsx
>          isLegacy: isEyfs,
eyfs only exists in legacy

2024-04-04 09:36 UTC, JBR90 commented
![image](https://github.com/oaknational/Oak-Web-Application/assets/7987787/7e09c479-03f9-4b2f-b91a-2e8ad50cca60)
@jack-skerrett-oak - there's a small MV change to fix the keysatge title here, which could happen before or after this PR is in ?

2024-04-04 10:11 UTC, njblore approved these changes

2024-04-04 10:52 UTC, jack-skerrett-oak commented
> ![image](https://private-user-images.githubusercontent.com/7987787/319527576-7e09c479-03f9-4b2f-b91a-2e8ad50cca60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjc4MDUsIm5iZiI6MTcxMjIyNzUwNSwicGF0aCI6Ii83OTg3Nzg3LzMxOTUyNzU3Ni03ZTA5YzQ3OS0wM2Y5LTRiMmYtYjkxYS0yZThhZDUwY2NhNjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMTA0NTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGJlZTk4M2MyNTk3NTJlZWZmY2UwNGFiY2FjNTAzYjBmZmFjOWFhNzA1YTM5YmFmMmU3MjY5ZDAyZjA0Zjc2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mNrXxqvVJMCrKfiGt3DFGeZbVktU0pdnYurFcyziqco) @jack-skerrett-oak - there's a small MV change to fix the keysatge title here, which could happen before or after this PR is in ?

@JBR90 I think for this one I would be on the side of making the MV change... I imagine people will be annoyed if it changes to "KS", I know it feels like wasted effort but probably should be done prior to the PR merge

2024-04-04 10:53 UTC, JBR90 commented
@jack-skerrett-oak Sure, no problem

2024-04-05 09:57 UTC, jack-skerrett-oak requested changes
There seems to be an issue with legacy KS4 maths. It takes you to the programme listing page for new maths. Same for combined science KS4

2024-04-05 10:40 UTC, JBR90 commented
> There seems to be an issue with legacy KS4 maths. It takes you to the programme listing page for new maths. Same for combined science KS4

Looks like these two programmes are missing the legacy prefix on the database, i've flagged it with the other squads and have added fix for these programmes for now.

2024-04-05 11:10 UTC, jack-skerrett-oak approved these changes

2024-04-05 12:40 UTC, merged

2024-04-05 12:42 UTC, oak-machine-user commented
:tada: This PR is included in version 1.401.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.401.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: