Feat/lesq 729/legacy search [LESQ-729]
oaknational/Oak-Web-Application pull request #2357
Opened 2024-04-11 07:52 UTC by njblore

## Description

Music year: {owa_music_year}

- remove call to 2020 search api
- update legacy filter to exclude EYFS only
- remove all 2020 search api code
- update all tests to use 2023 fixture and refactor some functionality to be shared

## How to test

Once the search API changes have been deployed to production:

1. Go to {owa_deployment_url}
2. Search for eg 'volcanoes'
3. You should see legacy results, once each (no duplicates)
4. in the requests tab you should only see requests to one search API
5. you should still see results for non-legacy content
6. if you search for eg 'veggies' you should get no results (EYFS content)

2024-04-12 08:36 UTC, k-huggs commented on src/context/Search/search-api/2023/fetchResults.ts
> +  const snakeaseData = snakecaseKeys(transformedData, {
not end of the world but small typo I think this should be snakecase

2024-04-12 08:39 UTC, k-huggs commented on src/context/Search/useSearch.test.ts
> +  test.skip("results should be returned in the correct form", async () => {
Do we need a note as to why this test is being skipped?

2024-04-12 08:39 UTC, k-huggs approved these changes

2024-04-17 12:01 UTC, njblore commented
@jack-skerrett-oak the qa testing is only on staging so won't be on prod, shall I ignore it anyway to be safe?
And yes agreed the computing subjects in particular are out of control

2024-04-17 14:30 UTC, njblore commented
@jack-skerrett-oak that 'qa test' subject is only published on staging, right?

2024-04-17 15:44 UTC, jack-skerrett-oak requested changes
Bit of an odd one. The maths units now show the core tier, great. However, there is at least one example I have found where a [unit](https://www.thenational.academy/teachers/programmes/maths-secondary-ks4-core-l/units/simplifying-surds-71e6/lessons) that appears in both Core and Higher has two different search results, one for core and one for higher rather than them being in a drop down. Other units (like Directed numbers) correctly have the drop down for picking between core and foundation. 
![Screenshot 2024-04-17 at 16 40 44](https://github.com/oaknational/Oak-Web-Application/assets/102532470/247b040a-a1d3-49c6-8e75-aaf009f8b30c)

2024-04-18 07:45 UTC, jack-skerrett-oak commented
> units

@njblore Ah OK, I didn't pick up on that. I guess it's fine for now though it does highlight we might need to be clearer on search results eventually

2024-04-18 07:45 UTC, jack-skerrett-oak approved these changes

2024-04-18 08:08 UTC, merged

2024-04-18 08:10 UTC, oak-machine-user commented
:tada: This PR is included in version 1.409.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.409.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: