Fix/lesq 748/search results a11y
oaknational/Oak-Web-Application pull request #2368
Opened 2024-04-18 09:58 UTC by njblore

## Description

Music year: {owa_music_year}

- update aria label for single search results 
- update aria label for drop down search results

## How to test

1. Go to {owa_deployment_url}
2. Search for eg 'surds'
3. You should see the aria label of 'see unit' is eg `see unit: simplifying surds`
4. Same for lessons
5. for results with a dropdown (tier or exam board) it should say `select tier for unit: simplifying surds` 

## Screenshots

How it should now look:

Lesson:
<img width="600" alt="Screenshot 2024-04-18 at 10 54 43" src="https://github.com/oaknational/Oak-Web-Application/assets/45038878/c9564754-8d22-49d1-872b-94b5a5b069f9">

Unit:
<img width="600" alt="Screenshot 2024-04-18 at 10 54 28" src="https://github.com/oaknational/Oak-Web-Application/assets/45038878/ca864395-3111-4ecc-aa92-3371c4ad9b6a">

Exam board:
<img width="600" alt="Screenshot 2024-04-18 at 10 55 49" src="https://github.com/oaknational/Oak-Web-Application/assets/45038878/038c1eaa-d900-4e9f-8806-b5d945e0e81c">

Tier:
<img width="600" alt="Screenshot 2024-04-18 at 10 54 05" src="https://github.com/oaknational/Oak-Web-Application/assets/45038878/31b638ad-bce2-4581-a9e5-0e1aa519f7fc">

2024-04-18 10:24 UTC, JBR90 approved these changes

2024-04-19 08:07 UTC, jack-skerrett-oak requested changes
Sorry, might not have been clear on the ticket. When you have a tier or exam board, we still need to say the unit name, so "See exam board for unit: [unit name]" otherwise the user has little/no knowledge of which lesson or unit they are selecting for

2024-04-23 08:01 UTC, jack-skerrett-oak approved these changes

2024-04-23 09:26 UTC, merged

2024-04-23 09:28 UTC, oak-machine-user commented
:tada: This PR is included in version 1.413.3 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.413.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: