feat: search filters from oak components
oaknational/Oak-Web-Application pull request #2400
Opened 2024-04-30 08:15 UTC by JBR90

## Description

Music year: {owa_music_year}

- uses Oak Components search filter checkbox
- Updated designs for search page 
- Move Unit and Lesson below search bar
- Refactor search events for new component 

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-04-30 12:33 UTC, k-huggs commented on src/components/TeacherComponents/SearchFilters/SearchFilters.tsx
> +          // $mt={["space-between-l", null]}
could remove comment if not required

2024-04-30 15:26 UTC, Monika-Koziol requested changes
Filters are looking good. There were a couple of weird things that might not be part of this ticket:

- [ ] strange cropped 'no results' underneath the nav, see attached screenshot
![Screenshot 2024-04-30 at 16 19 25](https://github.com/oaknational/Oak-Web-Application/assets/125288018/8e99c3f1-ac6a-4981-bc8f-ed848363bfca)

- [ ] is it possible to have [showing X results] closer to the unit/lesson filter with a larger gap away from the actual results? I can write another ticket for that if this was not part of this one.

2024-04-30 15:35 UTC, JBR90 commented
@Monika-Koziol - [ ] is it possible to have [showing X results] closer to the unit/lesson filter with a larger gap away from the actual results? I can write another ticket for that if this was not part of this one.

Sure, what distance do you want it be be ?

2024-05-01 10:07 UTC, k-huggs approved these changes

2024-05-01 10:56 UTC, jack-skerrett-oak requested changes
There are some general spacing issues with the top part of search that could potentially do with some looking at, but I might post about that in the squad channel, I know Monika mentioned it.

- [ ] I think we could get rid of the alt text on the subject icons on the search filters

2024-05-01 11:02 UTC, JBR90 commented
@jack-skerrett-oak Is Alt="" ok?

2024-05-01 11:08 UTC, jack-skerrett-oak commented
@JBR90 Yep should be!

2024-05-01 14:55 UTC, JBR90 commented
> @jack-skerrett-oak Is Alt="" ok?

Will happen with the next component release

2024-05-01 14:57 UTC, jack-skerrett-oak approved these changes
With the understanding that the alt text will be changed at next release due to oak-components NPM weirdness and that we will be defining better spacing on another ticket because it isn't all that relevant to this ticket.

2024-05-02 08:05 UTC, Monika-Koziol approved these changes

2024-05-02 08:06 UTC, merged

2024-05-02 08:08 UTC, oak-machine-user commented
:tada: This PR is included in version 1.426.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.426.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: