Feat sticky nav for new plan a lesson
oaknational/Oak-Web-Application pull request #2416
Opened 2024-05-09 13:52 UTC by JBR90

## Description

Music year: {owa_music_year}

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-05-09 14:24 UTC, njblore approved these changes

2024-05-09 14:24 UTC, njblore commented on src/__tests__/pages/lesson-planning-new.test.tsx
> +    expect(screen.getAllByText("Contents")).toHaveLength(2);
feels like getByRole 'nav' could work here?

2024-05-09 14:44 UTC, Monika-Koziol approved these changes

2024-05-10 07:40 UTC, njblore commented on src/__tests__/pages/lesson-planning-new.test.tsx
> +    expect(screen.getAllByText("Contents")).toHaveLength(2);
hmm just looked and it's actually role 'navigation', is that what you tried?

2024-05-10 08:04 UTC, jack-skerrett-oak approved these changes
Some a11y bits!

- Because the nav has been given `tabindex=0`, when tabbing through the page (with and without a screen reader) you are navigated to it even though you cannot interact with it and we don't want to be able to focus non-interactive elements
- I think it would be good to add [`aria-current=page`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) to the selected link in the nav to indicate to a screen reader user that this element is where you currently are. We are going to be doing a similar thing for the l[esson overview nav](https://www.notion.so/oaknationalacademy/I-want-the-lesson-overview-page-nav-to-be-accessible-6bbde63b08fb499e852b48454dbb4067?pvs=4)
- There are `aria-label`s on the lis, I am not sure what they are doing. This means that a screen reader is currently reading "Lesson planning is important, list item 1". If we wanted to make it really clear these are items in a nav list, we could say `aria-label="Scroll to lesson planning is important"` but I don't think it is needed per se

2024-05-10 08:04 UTC, jack-skerrett-oak requested changes
I approved but meant to request changes, whoops!

2024-05-13 08:05 UTC, jack-skerrett-oak approved these changes

2024-05-13 12:16 UTC, merged

2024-05-13 12:18 UTC, oak-machine-user commented
:tada: This PR is included in version 1.432.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.432.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: