Feat/pupil 680/style programme page b
oaknational/Oak-Web-Application pull request #2425
Opened 2024-05-15 11:05 UTC by benprotheroe

## Description

Music year: {owa_music_year}

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-05-15 12:17 UTC, benprotheroe commented on src/components/PupilComponents/BrowseExamboardSelector/BrowseExamboardSelector.tsx
> +              <OakPupilJourneyYearButton
all ive done here is swap out the oakSecondarybutton for the OakYearButton; and removed the container so the list items are rendered as the children to the programme options component

2024-05-15 12:18 UTC, benprotheroe commented on src/components/PupilViews/PupilLessonListing/PupilLessonListing.view.tsx
> -  }
swapped this around so the breadcrumb is consistent

2024-05-15 12:41 UTC, benprotheroe commented on src/components/PupilViews/PupilProgrammeListing/PupilProgrammeListing.view.tsx
> +  const topNavSlot = () => {
all the changeable objects are handled by these switch functions and theyre called with the jsx

2024-05-15 12:57 UTC, messmike commented
cheers @benprotheroe just a couple of things from me:

2024-05-15 13:28 UTC, RBrownsett commented
@benprotheroe any chance the Choose a tier heading can be bumped to H2 rather than H1? Saves us having to H1's on the page which can be confusing for screen readers 

![image](https://github.com/oaknational/Oak-Web-Application/assets/30384846/bff4634a-6962-4ba4-8f4d-4f7cfde95457)

2024-05-15 13:35 UTC, kimon-satan requested changes
A few minor points.

2024-05-15 13:35 UTC, kimon-satan commented on src/components/PupilComponents/BrowseTierSelector/BrowseTierSelector.tsx
> +  // const phaseSlug = programmes[0]?.programmeFields.phaseSlug;
delete this commented out code

2024-05-15 13:35 UTC, kimon-satan commented on src/components/PupilViews/PupilProgrammeListing/PupilProgrammeListing.view.tsx
> +      <AppLayout
Could we keep this at the page level. It's confusing when we're inconsistent. Should be cut and pasteable.

2024-05-15 13:35 UTC, kimon-satan commented on src/components/PupilViews/PupilProgrammeListing/PupilProgrammeListing.view.tsx
> +              {BrowseOptions()}
This should be implemented as React Function Component
ie. <BrowseOptions/>

2024-05-15 13:54 UTC, messmike approved these changes

2024-05-15 15:38 UTC, RBrownsett commented
@benprotheroe might not be a problem now (because currently we don't have any exam boards with our old content) but when you have selected a subject that has both a exam board and a tier - going back to the tier page from the unit page briefly shows the exam board page. Video below:

https://github.com/oaknational/Oak-Web-Application/assets/30384846/763f4e2c-d8d5-4b34-bd80-94b7424a6d45

2024-05-15 15:57 UTC, kimon-satan approved these changes

2024-05-16 07:12 UTC, RBrownsett commented
@benprotheroe noticed that the tooltip text is not fully viewable when in the mobile mode - I know we have PUPIL-701 to fix the tooltip - do we want to do something now or wait for that ticket?

![image](https://github.com/oaknational/Oak-Web-Application/assets/30384846/999a5f5e-37a0-458b-8be6-8a15177c4de5)

![image](https://github.com/oaknational/Oak-Web-Application/assets/30384846/35546d8e-d3d2-4a2f-b9fa-6a2f5f1b11d7)

2024-05-16 08:14 UTC, benprotheroe commented
> @benprotheroe might not be a problem now (because currently we don't have any exam boards with our old content) but when you have selected a subject that has both a exam board and a tier - going back to the tier page from the unit page briefly shows the exam board page. Video below:
> 
>  Biology.secondary.Year.10.-.Unit.listing._.Oak.National.Academy.-.15.May.2024.mp4



> @benprotheroe might not be a problem now (because currently we don't have any exam boards with our old content) but when you have selected a subject that has both a exam board and a tier - going back to the tier page from the unit page briefly shows the exam board page. Video below:
> 
>  Biology.secondary.Year.10.-.Unit.listing._.Oak.National.Academy.-.15.May.2024.mp4

have made a ticket to fix this: https://www.notion.so/oaknationalacademy/24-Spring-OKRs-Sprint-7-40f22700ac7a4168ad18accaa0c99296?p=fe795b6cfe394b9a904adabbfeed9ef4&pm=s

2024-05-16 08:16 UTC, benprotheroe commented
> @benprotheroe noticed that the tooltip text is not fully viewable when in the mobile/tablet mode - I know we have PUPIL-701 to fix the tooltip - do we want to do something now or wait for that ticket?
> 
> ![image](https://private-user-images.githubusercontent.com/30384846/331084532-999a5f5e-37a0-458b-8be6-8a15177c4de5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDc1OTgsIm5iZiI6MTcxNTg0NzI5OCwicGF0aCI6Ii8zMDM4NDg0Ni8zMzEwODQ1MzItOTk5YTVmNWUtMzdhMC00NThiLThiZTYtOGExNTE3N2M0ZGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA4MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NTk1YzM5MDVkNDE5OGQxM2NlOGE0MGY3ZWMyNmQyODQ0NmFiYjYzYTUxZjcyODMwNmNhNDhiNDE0MzhlNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j1KjENASeG7r2X5wNdHTmV0k6TtGqGZVJ8paSubKwSY)
> 
> ![image](https://private-user-images.githubusercontent.com/30384846/331085072-35546d8e-d3d2-4a2f-b9fa-6a2f5f1b11d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDc1OTgsIm5iZiI6MTcxNTg0NzI5OCwicGF0aCI6Ii8zMDM4NDg0Ni8zMzEwODUwNzItMzU1NDZkOGUtZDNkMi00YTJmLWI5ZmEtNmEyZjVmMWIxMWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA4MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNzFjYjFmNzkxNGQ1YjI2Nzc0M2EzOTAzYjkxM2M3Y2EyMDUxODVjOTI2YmE1MzYwM2IyMzVlMWYxOWYzZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.clojwZ4xvtqe1yQIKNe7bPQc86Fu95oJRHGym2GDKWQ)
> 
> ![image](https://private-user-images.githubusercontent.com/30384846/331106372-51fb8fcb-e681-4051-88bb-0868c96e0b21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NDc1OTgsIm5iZiI6MTcxNTg0NzI5OCwicGF0aCI6Ii8zMDM4NDg0Ni8zMzExMDYzNzItNTFmYjhmY2ItZTY4MS00MDUxLTg4YmItMDg2OGM5NmUwYjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDA4MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwM2JhNTRlZDNlNDFjZDNmOThjNzVjZTEyMzE0MWM4ZGMzYmQ0MTJiZjVkZjg0Nzg4MGM2MzgxNWU0MmE2MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mTq-9IHZl6YV27CnpIafxmUCgeBvEreDI48Vrfq28Zg)

either way the fix will be on oak components repo so i will make a ticket for now and we can fix prior to launch: https://www.notion.so/oaknationalacademy/24-Spring-OKRs-Sprint-7-40f22700ac7a4168ad18accaa0c99296?p=9c312489a3d64bbfa9fa7f5c91856657&pm=s

2024-05-16 08:17 UTC, merged

2024-05-16 08:19 UTC, oak-machine-user commented
:tada: This PR is included in version 1.435.1 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.435.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: