Feat/lesq 914/share all to pupils [LESQ-914]
oaknational/Oak-Web-Application pull request #2553
Opened 2024-07-01 13:16 UTC by njblore

## Description

Music year: {owa_music_year}

- remove hardcoded list of subjects which can be shared to the new pupil experience
- remove conditional usage of new pupil experience for share links
- remove code related to selecting resources to share as the new pupil experience does not support this

## How to test

1. Go to https://deploy-preview-2553--oak-web-application.netlify.thenational.academy/teachers/programmes/rshe-pshe-secondary-ks4-l/units/being-safe-informed-consent-6fd6/lessons/sexual-consent-and-capacity-to-consent-61j3ec/share?preselected=all
2. Click on preview as a pupil, or one of the share options
3. You should be directed to the new pupil experience version of the lesson instead of the home page

## Checklist

- [ ] All legacy content can be shared to the pupil view
- [ ] Remove all the custom code that was handling subject by subject restrictions on share
- [ ] Change header to be “Share your lesson” and remove “Select online activities”

2024-07-01 14:37 UTC, rightsaidjames requested changes
@njblore The requirements say to change the main heading to 'Share your lesson' and to remove the 'Select online activities' sub-headings, but there are still two headings and the main heading still just says 'Share':
![Screenshot 2024-07-01 at 15 35 18](https://github.com/oaknational/Oak-Web-Application/assets/3018395/7cf8aca1-e76d-41eb-950a-4ca3c5ba5a43)

2024-07-01 14:58 UTC, njblore commented
> @njblore The requirements say to change the main heading to 'Share your lesson' and to remove the 'Select online activities' sub-headings, but there are still two headings and the main heading still just says 'Share'

thanks @rightsaidjames , totally misread that requirement! 🤦‍♀️ should be correct now

2024-07-01 15:51 UTC, RBrownsett approved these changes
Approved - tested on RHSE lessons, share link works as expected. Also checked that legacy and new content still worked as expected for other subjects.

2024-07-02 08:16 UTC, rightsaidjames approved these changes

2024-07-02 08:24 UTC, JBR90 approved these changes

2024-07-02 12:18 UTC, merged