fix(units): fix unit text for legacy and cycle 1 unit list
oaknational/Oak-Web-Application pull request #2591
Opened 2024-07-04 13:43 UTC by benprotheroe

## Description

Music year: {owa_music_year}

- List of changes

## Expected behaviour

- **New** curriculum unit title should read “**Choose a unit**“
- **Legacy** curriculum unit title should read “**Choose a previously released unit**“

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}/pupils/programmes/geography-primary-year-4/units
1. Go to {owa_deployment_url}/pupils/programmes/maths-secondary-year-10-foundation-l/units
4. You should see the counter text is either previously released.. or just choose a unit depending on whether your on a legay or cycle 1 programme page

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-07-04 13:53 UTC, BTitterington approved these changes

2024-07-04 14:02 UTC, RBrownsett requested changes
@benprotheroe testing the first link the text still reads as 'choose a legacy unit' rather than 'choose a previously released unit'? 
![image](https://github.com/oaknational/Oak-Web-Application/assets/30384846/62b7a922-4d6a-4606-a222-376fd36fea04)

2024-07-04 16:00 UTC, RBrownsett commented
@benprotheroe looking good - the only thing is now all legacy units show the text 'choose a previously released unit' even when there is no cycle 1 content. For example year 1 art only has legacy:
Deployed: 
![image](https://github.com/oaknational/Oak-Web-Application/assets/30384846/57d6fcfd-0957-4319-98e4-441fd170bcab)
 
Live:
![image](https://github.com/oaknational/Oak-Web-Application/assets/30384846/e55ae9a1-1df7-418a-adfc-f05f85d984c9)

Is it possible for the legacy only just to show choose a unit or is that a complicated change to make?

2024-07-08 07:47 UTC, merged

2024-07-08 07:49 UTC, oak-machine-user commented
:tada: This PR is included in version 1.477.1 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.477.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: