Feat/lesq 962/combined unit listing pages [LESQ-962]
oaknational/Oak-Web-Application pull request #2647
Opened 2024-07-30 08:14 UTC by njblore

## Description

Music year: {owa_music_year}

- remove custom logic for maths on subject listing and unit listing pages and promote for all subjects
- remove legacy flag from subject listing page query and simplify
- refactor subject card double to just a single
- refactor props for subject card
- refactor unit listing page and add tests for helper methods

## How to test

note: ks4 science subjects are a bit unique, we are going to remove the singular legacy units as they are replicated in the 'new' curriculum, this means there are technically programmes which are unreachable through this new journey but that is fine (also the counts for the unit and lessons will be incorrect on the combined listing until those units are taken down)

1. Go to subject listing pages eg {owa_deployment_url}/teachers/key-stages/ks2/subjects
3. You should see all subjects are combined into a single card
4. EYFS should be all legacy
5. Specialist should be unaffected  {owa_deployment_url}/teachers/specialist/subjects
6. Subjects with programmes should proceed to correct programme listing page
7. Unit listing page should correctly group legacy and new units

## Screenshots

How it used to look (delete if n/a):
<img width="600" alt="Screenshot 2024-07-30 at 09 10 02" src="https://github.com/user-attachments/assets/f495a547-d8b1-44ee-a901-3de809b93231">
<img width="600" alt="Screenshot 2024-07-30 at 09 10 49" src="https://github.com/user-attachments/assets/292fd27d-d91d-460a-95aa-2f1d66348e81">

How it should now look:

<img width="600" alt="Screenshot 2024-07-30 at 09 10 30" src="https://github.com/user-attachments/assets/172ef200-931a-4d96-956e-1257c7c7ad04">
<img width="600" alt="Screenshot 2024-07-30 at 09 10 59" src="https://github.com/user-attachments/assets/b843633c-cd11-4184-90c2-dedf134249a2">

## Checklist

- [ ] Only display ‘new’ threads
- [ ] Add link for new/legacy curriculum pages
- [ ] Change subject card to be one button

2024-08-05 10:14 UTC, RBrownsett requested changes
@JBR90 couple of issues from initial testing:

1. Specialised subjects - the new unit card has bee applied but the formatting looks incorrect without padding:
![image](https://github.com/user-attachments/assets/f60ee88a-e1ca-4d9b-a37e-720b384ad034)
2. The year identifier is missing from the top of the unit card that has optionality units (should be just to the right of the the number of unit options info) 
![image](https://github.com/user-attachments/assets/c0b89e59-8bdd-4c7e-990e-af5da440ef1f)
3. The disabled functionality for the unit cards seems not be working. Units that should be 'greyed out' and disabled can be clicked on and you are taken to the lesson listing page. Art KS3 example below - unit one should be greyed out: 
PR:
![image](https://github.com/user-attachments/assets/e39f6b5c-73d4-4c48-b266-c2a92c5cf1a8)

Live:
![image](https://github.com/user-attachments/assets/0917330b-f70d-4dd2-8ed1-27bc7823b5eb)

2024-08-05 10:33 UTC, carlmw reviewed
Nothing blocking from a code perspective IMO. Happy to do another pass on any new commits once you've taken care of @RBrownsett's comments!

2024-08-05 10:33 UTC, carlmw commented on src/components/TeacherComponents/UnitList/helpers.tsx
> +};
🏄🏻 🤯 reading this broke me for a few reads. 

The argument name `legacy` obscures the intention (which I think is to let you filter out lessons with legacy slugs or vice versa).

The nested ternary hurt too. Could be refactored as an early return? 

```suggestion
export const getPageItems = (
  pageItems: CurrentPageItemsProps[] | SpecialistUnit[][],
  pickLegacyItems: boolean,
) => {
  if (!isCurrentPageItems(pageItems)) {
    return [];
  }

  return pageItems.filter((item) => {
    const isLegacy = isSlugLegacy(item[0]!.programmeSlug);
    return pickLegacyItems ? isLegacy : !isLegacy;
  });
};
```

2024-08-05 11:23 UTC, RBrownsett commented
@JBR90 another odd bug - navigating to an optionality unit then going from the lesson listing page back to the unit listing page the units are duplicated below the footer and we end up with two footers - see video below for behaviour (example KS4 English AQA)

https://github.com/user-attachments/assets/506bcff1-f721-4bcb-bdb7-45333e1be57a

2024-08-05 15:19 UTC, JBR90 commented on src/components/TeacherComponents/UnitList/UnitList.tsx
> +      // Tracking data was not being sent to avo before the page reload, so we prevent the default and use router to navigate to the page after the onClick
Thanks, will give it a read for next time

2024-08-07 09:44 UTC, RBrownsett commented
@JBR90 approved - changes have been made, great work! Testing notes detailed on the Notion ticket

2024-08-07 11:44 UTC, merged

2024-08-07 11:51 UTC, oak-machine-user commented
:tada: This PR is included in version 1.507.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.507.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: