Feat/lesq 1011/auth terms and conditions [LESQ-1011]
oaknational/Oak-Web-Application pull request #2716
Opened 2024-08-20 12:59 UTC by njblore

## Description

Music year: {owa_music_year}

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-08-21 10:56 UTC, JBR90 approved these changes

2024-08-21 12:13 UTC, k-huggs commented on src/browser-lib/hubspot/forms/getHubspotFormPayloads.ts
> -  schoolName: z.string().optional(),
Ahh meant to write a ticket for this, good catch!

2024-08-21 12:32 UTC, jack-skerrett-oak requested changes
- [ ] One thing to definitely fix, the focus state of the links acts more like it should for buttons than what we do for links
![Screenshot 2024-08-21 at 13 25 30](https://github.com/user-attachments/assets/b28a8e47-ea01-406c-9419-48bcd23c32d4)
- [ ] For some reason this deploy was really slow for me, unsure of the cause at the moment, but what that made me realise is that the T&Cs section loads in before the form, and it was sometimes a few seconds before the sign up form was displayed, you can see it happen very quickly in this video (github doesn't seem to want to play videos anymore, annoying!) This is especially frustrating when a user signs up and the clerk page is displayed briefly (dependent on the speed of the process) with the acorn and just T&Cs displayed
https://github.com/user-attachments/assets/a0b2a2c3-af42-4c70-83cb-188e22ae89cc

2024-08-21 13:02 UTC, k-huggs approved these changes

2024-08-22 08:05 UTC, jack-skerrett-oak approved these changes

2024-08-22 08:06 UTC, merged

2024-08-22 08:13 UTC, oak-machine-user commented
:tada: This PR is included in version 1.528.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.528.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: