Feat/lesq 1040/optional onboarding step [LESQ-1040]
oaknational/Oak-Web-Application pull request #2764
Opened 2024-09-10 09:26 UTC by njblore

## Description

Music year: {owa_music_year}

- Adds a new page to to the onboarding journey 'How can oak support you'
- Optional list of multi select checkboxes
- Adds Skip button and subheading to onboarding form
- Only navigate to new page when not already signed up in hubspot

## How to test

1. Go to {owa_deployment_url}/onboarding *while signed in*
2. Click on Yes
3. 4. Fill out the school picker or manually enter school and continue

**Scenario 1**: Not subscribed to communications in Hubspot
5. You should be directed to the 'how can oak support you page'
6. Selecting options and clicking continue will send your selected options to hubspot
7. You should be able to click 'skip' which will submit your existing answers to hubspot

**Scenario 2:** Already subscribed to communications in Hubspot (no checkbox visible on the page)
5. You should be directed back to the home page without seeing the How can oak support you page
6. You hubspot submision will not include any data on how can oak support you

## Screenshots

How it should now look:
<img width="430" alt="Screenshot 2024-09-10 at 10 21 17" src="https://github.com/user-attachments/assets/33047503-1755-4043-9b06-0f628551bab1">

2024-09-10 11:06 UTC, Monika-Koziol requested changes
@njblore thanks for adding the error state. Great that it tells the user how to fix it. A few style changes:

- [ ] 'back link' in error message: can we make it red and underlined? 
- [ ] 'Select all that apply' can we change colour to --text-subdued, #575757)
- [ ] 'Select all that apply' extra bottom padding 16px

2024-09-10 13:10 UTC, RBrownsett approved these changes
Approved - tested all 3 test cases with no issues.

The only comment I would have is currently the 'Skip' button and 'Continue' button (with no options selected) do the same thing - direct the user to the homepage. Not sure if the plan is for the continue button to go to another page in the future? If not then would we want validation on the 'Continue' button asking the user to select one of the options? Just a thought.

2024-09-11 15:36 UTC, JBR90 approved these changes

2024-09-12 08:55 UTC, Monika-Koziol approved these changes

2024-09-12 08:56 UTC, merged

2024-09-12 08:58 UTC, oak-machine-user commented
:tada: This PR is included in version 1.544.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.544.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: