feat(results): add printable results page behind feature flag
oaknational/Oak-Web-Application pull request #2766
Opened 2024-09-11 09:54 UTC by benprotheroe

## Description

Music year: {owa_music_year}

- List of changes

## Issue(s)

Fixes #

## How to test

## NOTE NEEDS A MERGE FROM oak-pupil-client repo

1. Go to {owa_deployment_url}/pupils/programmes/maths-primary-year-6/units/use-knowledge-of-part-whole-structure-to-solve-additive-problems/lessons/explain-how-a-combination-of-different-parts-can-be-equivalent-to-the-same-whole/overview
2. Click on "share lesson result" button
3. You should see results page opened in a new tab

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-09-13 07:42 UTC, kimon-satan requested changes
I'm going to leave a few more comments on the PR description too

2024-09-13 07:42 UTC, kimon-satan commented on src/components/PupilViews/PupilReview/PupilReview.view.tsx
> +  const handleShareResultsClick = async () => {
Share is a confusing name here as what you're actually doing is generating printable results. Can we change all the references to 'share' to 'Printable' so this function would be renamed 'handlePrintableResultsClick'

2024-09-13 07:42 UTC, kimon-satan commented on src/components/PupilViews/PupilReview/PupilReview.view.tsx
> +                  Share lesson results
This should say 'Printable results'

2024-09-13 07:42 UTC, kimon-satan commented on src/pages/pupils/lessons/[lessonSlug]/results/[attemptId].tsx
> +const FeaturedCanonicalResultsPage = withFeatureFlag(
Actually we don't need the flag once we get to the page.  So just export CanonicalResultsPage as default and remove the rest

2024-09-13 07:42 UTC, kimon-satan commented on src/pages/pupils/programmes/[programmeSlug]/units/[unitSlug]/lessons/[lessonSlug]/results/[attemptId].tsx
> +const FeaturedResultsPage = withFeatureFlag(
As per above we don't need the feature flag here just export the ResultsPage as default.

2024-09-13 07:42 UTC, kimon-satan commented on src/components/PupilViews/PupilReview/PupilReview.view.tsx
> +  const isShowShareButton = useFeatureFlagEnabled("share-results-button");
This will be for share and printable results so I'd rename to a plural isShowShareButtons

2024-09-13 07:42 UTC, kimon-satan commented on src/components/PupilViews/PupilExperience/PupilExperience.view.tsx
> +          programmeSlug={browseData.programmeSlug}
lets just pass through the browse data and the page type for a cleaner interface

2024-09-13 07:42 UTC, kimon-satan commented on src/components/PupilViews/PupilReview/PupilReview.view.tsx
> +  programmeSlug: string;
As per my comment on pupil experience, lets just use browse data and pageType instead of all of these individual props.

2024-09-13 07:44 UTC, kimon-satan commented
I don't understand "NOTE NEEDS A MERGE FROM oak-pupil-client repo" . If this is the case then the PR is not ready for review.

2024-09-13 07:45 UTC, kimon-satan commented
There should be an equivalent production feature flag with the same name. Can you link to it here so that it can be reviewed.

2024-09-13 07:55 UTC, kimon-satan commented
Those conflicts will require mashing both bits of code together so be careful

2024-09-13 07:58 UTC, kimon-satan commented
Final one - can we have a look at  src/browser-lib/pupil-api/PupilClientProvider.tsx . I'm not convinced that we need this wrapper. But in any case it needs to be renamed to something less confusing.

2024-09-16 08:49 UTC, RBrownsett commented
@benprotheroe looking good. From an accessibility point of view does the button need to open the results in a new tab? If so can we add some warning text for screen readers to inform the user that the results will be displayed in a new tab - e.g. 

```
<button 
  class="sc-jxOSlx sc-gFAWRd fcakBG iAbZPB internal-button" 
  type="button"
  aria-label="Printable results, opens in a new tab"
  title="Printable results (opens in a new tab)">
  <div class="sc-fqkvVR sc-gsFSXq JTNJX hZMTYx">
    <span class="sc-kpDqfm cYGSwL">Printable results</span>
  </div>
</button>
```

Also adding a visual cue that the results open in a new tab could be useful - 

![image](https://github.com/user-attachments/assets/b0919eb6-9621-4c23-9d01-27e35e656883)

Further information about opening links in new tabs here:

https://www.digitala11y.com/external-links-in-or-out/

2024-09-16 08:57 UTC, benprotheroe commented
> @benprotheroe looking good. From an accessibility point of view does the button need to open the results in a new tab? If so can we add some warning text for screen readers to inform the user that the results will be displayed in a new tab - e.g.
> 
> ```
> <button 
>   class="sc-jxOSlx sc-gFAWRd fcakBG iAbZPB internal-button" 
>   type="button"
>   aria-label="Printable results, opens in a new tab"
>   title="Printable results (opens in a new tab)">
>   <div class="sc-fqkvVR sc-gsFSXq JTNJX hZMTYx">
>     <span class="sc-kpDqfm cYGSwL">Printable results</span>
>   </div>
> </button>
> ```
> 
> Also adding a visual cue that the results open in a new tab could be useful -
> 
> ![image](https://private-user-images.githubusercontent.com/30384846/367694144-b0919eb6-9621-4c23-9d01-27e35e656883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzY4NDgsIm5iZiI6MTcyNjQ3NjU0OCwicGF0aCI6Ii8zMDM4NDg0Ni8zNjc2OTQxNDQtYjA5MTllYjYtOTYyMS00YzIzLTlkMDEtMjdlMzVlNjU2ODgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA4NDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZTk4NzJlZDU1YWI0ZTRhNGJkZjI0ZTA2NmEwNjNmMDUwNjJkYTc1NTFmMTE1NDdlM2QyNjIwMTE3YTdlMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i2hFPIThj1eRpDjhjEDqvB7SYmqYSSx1rXKghLUKazI)
> 
> Further information about opening links in new tabs here:
> 
> https://www.digitala11y.com/external-links-in-or-out/

really good point; when i was building i didnt think of it as a link; because the it calls a function which stores the lesson attempt; but then once its stored it open the page; but i guess from a ux it feels like a normal link; would it be suficient from an accessibility pov to add the external link logo; and add a note for the screenreader which says will open a new tab with reults on it. or do we have to change the role of the button to link as well?

2024-09-16 09:36 UTC, benprotheroe commented
> > > @benprotheroe looking good. From an accessibility point of view does the button need to open the results in a new tab? If so can we add some warning text for screen readers to inform the user that the results will be displayed in a new tab - e.g.
> > > ```
> > > <button 
> > >   class="sc-jxOSlx sc-gFAWRd fcakBG iAbZPB internal-button" 
> > >   type="button"
> > >   aria-label="Printable results, opens in a new tab"
> > >   title="Printable results (opens in a new tab)">
> > >   <div class="sc-fqkvVR sc-gsFSXq JTNJX hZMTYx">
> > >     <span class="sc-kpDqfm cYGSwL">Printable results</span>
> > >   </div>
> > > </button>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also adding a visual cue that the results open in a new tab could be useful -
> > > ![image](https://private-user-images.githubusercontent.com/30384846/367694144-b0919eb6-9621-4c23-9d01-27e35e656883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzY4NDgsIm5iZiI6MTcyNjQ3NjU0OCwicGF0aCI6Ii8zMDM4NDg0Ni8zNjc2OTQxNDQtYjA5MTllYjYtOTYyMS00YzIzLTlkMDEtMjdlMzVlNjU2ODgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA4NDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZTk4NzJlZDU1YWI0ZTRhNGJkZjI0ZTA2NmEwNjNmMDUwNjJkYTc1NTFmMTE1NDdlM2QyNjIwMTE3YTdlMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i2hFPIThj1eRpDjhjEDqvB7SYmqYSSx1rXKghLUKazI)
> > > Further information about opening links in new tabs here:
> > > https://www.digitala11y.com/external-links-in-or-out/
> > 
> > 
> > really good point; when i was building i didnt think of it as a link; because it calls a function which stores the lesson attempt; but then once its stored it open the page; but i guess from a ux it feels like a normal link; would it be suficient from an accessibility pov to add the external link logo; and add a note for the screenreader which says will open a new tab with reults on it. or do we have to change the role of the button to link as well?
> 
> Yeah from a user point of view it feels like the behaviour is closer to a link rather than a button, its navigating to a new tab with a different url so it would make sense from a semantic point of view for it to be anchor () tag rather than a button

It cant be a anchor tag because the href doesnt exiat until you ve clicked the button; the callback function creates the href;

2024-09-16 10:22 UTC, kimon-satan approved these changes
I approved but could you make the one small change I commented on pls.

2024-09-16 10:22 UTC, kimon-satan commented on src/components/PupilViews/PupilReview/PupilReview.view.tsx
> +      phase={phase as "primary" | "secondary"}
don't cast . resolve the ts error by throwing an error if the phase isn't primary or secondary

2024-09-16 10:33 UTC, merged

2024-09-16 10:35 UTC, RBrownsett reviewed
Approved - accessibility of button has been improved and user is informed that a new tab will open

2024-09-16 10:40 UTC, oak-machine-user commented
:tada: This PR is included in version 1.547.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.547.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: