Chore/lesq 1067/update meta descriptions [LESQ-2067]
oaknational/Oak-Web-Application pull request #2802
Opened 2024-09-19 13:16 UTC by njblore

## Description

Music year: {owa_music_year}

- Update meta seo descriptions on the teachers tab and keystage subject pages
- Also updated default homepage SEO in config

## How to test

1. Go to {owa_deployment_url}
2. meta description should be "Browse and download our lesson planning resources, view our curriculum plans and explore our AI lesson assistant - all optional, free and adaptable."
3. Go to /teachers
4. meta title should be 'Free, time-saving teacher resources | Oak National Academy', meta description should be 'Explore our free, time-saving teacher resources from Oak National Academy. Browse and download worksheets, quizzes and slides from KS1 to KS4. '
5. Go to /teachers/key-stages/ks2/subjects
6. meta description should be 'Click here to browse and download our free KS2 teaching resources for lesson planning. Our teaching resources are made by subject experts and entirely free to download and use.'

## Checklist
Meta descriptions should be correct on:
- [ ] Homepage (AI)
- [ ] Teachers tab
- [ ] subject listing pages

2024-09-19 14:26 UTC, k-huggs approved these changes

2024-09-23 12:15 UTC, mikeritson-oak requested changes
The changes all looked good for the KS1-KS4 pages but we also have a EYFS that was showing in the code as `EARLY-YEARS-FOUNDATION-STAGE`, rather than a user friendly format. I see four references in the head section and one further down the page.
![image](https://github.com/user-attachments/assets/b9e2b1c7-de73-4222-b6e9-9aa8c3830492)
It has been agreed within the squad to update these to the user friendly `EYFS` for these instances of the slug.

2024-09-23 13:37 UTC, mikeritson-oak approved these changes
Checked and confirmed on the preview branch and it all looks good to go. 👍

2024-09-23 13:48 UTC, merged

2024-09-23 13:50 UTC, oak-machine-user commented
:tada: This PR is included in version 1.558.1 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.558.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: