fix(LESQ-1082): only render filter heading when options
oaknational/Oak-Web-Application pull request #2814
Opened 2024-09-24 13:29 UTC by k-huggs

## Description

Music year: {owa_music_year}

- Conditionally renders filter title based on if filters are available

## Issue(s)

Fixes #LESQ-1082

## Acceptance Criteria:

When there are no filter options available for a subject do not show filter heading

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
![image](https://github.com/user-attachments/assets/e700da82-f267-4a60-8f8c-e49326359d25)

How it should now look:

<img width="1292" alt="Screenshot 2024-09-24 at 14 28 56" src="https://github.com/user-attachments/assets/7aefac7d-843b-400e-a646-902e6568bb5a">

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-09-24 15:31 UTC, k-huggs commented on src/pages/teachers/programmes/[programmeSlug]/units.tsx
> +    subjectCategories?.length > 1 ||
hmm think this was copilot being a bit over zealous, not sure how the type checker didn't catch this

2024-09-24 16:09 UTC, carlmw commented on src/pages/teachers/programmes/[programmeSlug]/units.tsx
> +    subjectCategories?.length > 1 ||
it will narrow it to an array so it wont actually produce an error, more a job for a linter to pick up extraneous optional chaining

2024-09-26 13:25 UTC, jack-skerrett-oak approved these changes

2024-09-26 13:26 UTC, jack-skerrett-oak requested changes
Sorry, removing my approval. You'll need to remove the filter drop down from mobile widths as well!

2024-09-26 14:18 UTC, k-huggs commented
> Sorry, removing my approval. You'll need to remove the filter drop down from mobile widths as well!

removed ✅

2024-09-26 14:30 UTC, jack-skerrett-oak approved these changes

2024-09-26 14:43 UTC, merged