Added "video" and "partner bio" to curriculum overview table of contents
oaknational/Oak-Web-Application pull request #2855
Opened 2024-10-07 10:43 UTC by orangemug

## Description
Added "video" and "partner bio" to curriculum overview table of contents

<img width="1328" alt="Screenshot 2024-10-07 at 11 41 19" src="https://github.com/user-attachments/assets/45155a7d-ec7f-4e89-b1b9-a72ee256986b">

## Issue(s)

Fixes `CUR-939`

## How to test
Cycle 1

1. Go to {owa_deployment_url}
2. Check for regressions

Cycle 2

1. Checkout locally with `ENABLE_CYCLE_2=true`
2. Check "Video Guide" and "Our curriculum partner" work as expected in all viewport sizes

2024-10-07 10:52 UTC, sonalisin approved these changes

2024-10-07 14:24 UTC, rightsaidjames requested changes
In addition to the below copy change, I've noticed that the table of contents buttons (that will eventually be links) don't have focus styles, which is a major a11y violation. Happy for this to be fixed in another ticket, but I'd strongly prefer we don't go live with it.

2024-10-07 14:24 UTC, rightsaidjames commented on src/components/CurriculumComponents/OverviewTab/OverviewTab.tsx
> +      children: [{ text: "Video Guide" }],
Sentence case!
```suggestion
      children: [{ text: "Video guide" }],
```

2024-10-09 09:46 UTC, rightsaidjames approved these changes
Looks good - the TOC now behaves identically to the 'plan a lesson' page table of contents, with fully accessible links (rather than buttons). The Video guide (where relevant) and Our curriculum partners sections are present in the list and take the user to the right part of the page in all viewports.

2024-10-15 10:48 UTC, rightsaidjames approved these changes
Retested alongside #2865 after rebase - LGTM

2024-10-15 10:48 UTC, merged

2024-10-15 10:55 UTC, oak-machine-user commented
:tada: This PR is included in version 1.591.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.591.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: