All years in mobile header and unit modal
oaknational/Oak-Web-Application pull request #2869
Opened 2024-10-10 12:45 UTC by orangemug

## Description
Adds all-years alternative text in mobile header and unit modal

## Issue(s)

Fixes `CUR-959`

## How to test
 - Enable cycle 2 and test for correct text in mobile header and unit modal.
 - Check for regressions in cycle 1

2024-10-11 07:54 UTC, rightsaidjames requested changes
@orangemug Mostly good but, as per the [Figma designs](https://www.figma.com/design/3cz9fb0ObFDLv1c212OtJv/Final-designs---Curriculum-squad?node-id=6242-93342&m=dev) on mobile, the subject and year group need to stack in the unit modal header so that they don't get crammed into a single row:

![Screenshot 2024-10-10 at 17 37 40](https://github.com/user-attachments/assets/97a71523-ca98-42a0-8215-8accf1c5fab8)

![Screenshot 2024-10-11 at 08 51 33](https://github.com/user-attachments/assets/c96ac265-b5eb-4544-88fc-0a00a64aecc0)

2024-10-14 09:05 UTC, sonalisin approved these changes

2024-10-15 11:13 UTC, rightsaidjames approved these changes
Looks good, wraps well on all mobile viewports.

2024-10-15 13:03 UTC, merged

2024-10-15 13:05 UTC, oak-machine-user commented
:tada: This PR is included in version 1.592.1 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.592.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: