feat: consolidate thread and year group screen reader announcements
oaknational/Oak-Web-Application pull request #2947
Opened 2024-10-30 15:40 UTC by assadk88

## Description

Music year: {owa_music_year}

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-10-30 16:06 UTC, rightsaidjames requested changes
I've made some suggested improvements to reduce unnecessary verbosity. But other than that I've tested it with VoiceOver and it works perfectly!

2024-10-30 16:07 UTC, assadk88 commented on src/components/CurriculumComponents/UnitsTab/UnitsTab.tsx
> +            </ScreenReaderOnly>
Sounds good to me!

2024-10-31 09:43 UTC, orangemug approved these changes

2024-10-31 16:28 UTC, rightsaidjames approved these changes
LGTM!

2024-10-31 16:38 UTC, merged

2024-10-31 16:40 UTC, oak-machine-user commented
:tada: This PR is included in version 1.613.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.613.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: