feat: create media page
oaknational/Oak-Web-Application pull request #2992
Opened 2024-11-14 10:31 UTC by weronika-szalas

## Description

Music year: {owa_music_year}

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-11-19 11:09 UTC, k-huggs requested changes

2024-11-19 11:09 UTC, k-huggs commented on src/components/TeacherViews/LessonMedia/LessonMedia.view.tsx
> +    <Box $ph={[16, null]}>
Is it possible to refactor with component lib components i.e. `OakBox`, `OakMaxWidth` etc

2024-11-19 12:06 UTC, RBrownsett approved these changes
Tested - feature flag in place in dev and currently not enabled in live. 

Tested base page with no issues

2024-11-20 13:33 UTC, k-huggs approved these changes

2024-11-20 15:00 UTC, merged

2024-11-20 15:01 UTC, oak-machine-user commented
:tada: This PR is included in version 1.630.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.630.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: