fix: set school to not listed in onboarding
oaknational/Oak-Web-Application pull request #3044
Opened 2024-12-02 12:33 UTC by dkyyau

## Description

Music year: {owa_music_year}

- List of changes
- Set schoolName and schoolId to `notListed` in local storage when selecting no school during onboarding

## Issue(s)

Fixes #

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-12-06 08:49 UTC, njblore approved these changes

2024-12-11 09:35 UTC, jack-skerrett-oak requested changes
It seems like the happy path is no longer working. If you sign up using the "Yes" path and supply a school from the school picker, it isn't saved in your local storage and you end up with "notListed"

2024-12-12 17:04 UTC, jack-skerrett-oak approved these changes
I'm approving this just because I think there is more harm leaving it open than closing it. It does the happy journeys and sets things as expected (most of the time).

2024-12-12 17:45 UTC, merged

2024-12-12 17:47 UTC, oak-machine-user commented
:tada: This PR is included in version 1.650.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.650.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: