CTC-92: Lesson overview vocab button component
oaknational/Oak-Web-Application pull request #3053
Opened 2024-12-04 15:23 UTC by k-huggs

## Description

Music year: {owa_music_year}

- Adds `LessonOverviewVocabButton` component to `LessonDetails`
- OnClick should navigate to additional materials
- Updates `LessonDetails` test file

## Issue(s)

Fixes #CTC-92

## How to test

1. Go to {owa_deployment_url}
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

2024-12-05 12:41 UTC, weronika-szalas approved these changes

2024-12-06 11:31 UTC, RBrownsett requested changes
@k-huggs I'm seeing issues with mobile and tablet view - white space at the top of the page in tablet and the button does not fit correctly in mobile

tablet:
![image](https://github.com/user-attachments/assets/cb78dd47-3464-4c73-9d0c-4de2f7dbb844)

Mobile:
![image](https://github.com/user-attachments/assets/eac39875-5c5a-49f2-9090-99a9f9b29455)

2024-12-06 15:11 UTC, RBrownsett commented
Tested - issues with mobile view and tablet view have now been resolved

2024-12-06 16:16 UTC, merged

2024-12-06 16:19 UTC, oak-machine-user commented
:tada: This PR is included in version 1.644.0 :tada:

The release is available on [GitHub release](https://github.com/oaknational/Oak-Web-Application/releases/tag/v1.644.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: