Added "lot picker" to curric homepage
oaknational/Oak-Web-Application pull request #3076
Opened 2024-12-18 16:59 UTC by orangemug

## Description
Added "lot picker" to curriculum homepage

**Known issues**: The photo is still the old image, we should be able to test prior to that though

## Issue(s)

Fixes `CUR-1140`

## How to test

1. Go to {owa_deployment_url}/curriculum
2. Check picker is now displayed and works correctly
3. Check visuals are as outlined in `CUR-1140`

2025-01-02 09:22 UTC, rightsaidjames requested changes
Generally this looks good, but:
- At desktop viewports, the right edge of the lot picker is too near the poster image. Is this within the scope for this ticket @HelenHarlow / @orangemug ?
![Screenshot 2025-01-02 at 09 04 50](https://github.com/user-attachments/assets/d0710f9d-1245-48ce-8769-dcfaeafcf676)
![Screenshot 2025-01-02 at 09 07 29](https://github.com/user-attachments/assets/cc78e5c0-9b45-4877-93a5-6cc9023a7ad5)

2025-01-02 10:01 UTC, HelenHarlow commented
> * At desktop viewports, the right edge of the lot picker is too near the poster image. Is this within the scope for this ticket @HelenHarlow / @orangemug ?

@rightsaidjames interestingly I can't seem to replicate that, on desktop it looks like this for me:
<img width="1440" alt="Screenshot 2025-01-02 at 10 01 11" src="https://github.com/user-attachments/assets/8a00ef58-ee13-4c6a-b045-4bde3eedafb6" />

2025-01-02 10:22 UTC, rightsaidjames commented
@HelenHarlow How bizarre, I can reproduce it in Chrome and Firefox, but not Safari. Does it look okay in Chrome for you?

Chrome:
![Screenshot 2025-01-02 at 10 09 37](https://github.com/user-attachments/assets/2f3edde0-e63c-4204-93e0-9b4b7db04ef7)

Firefox:
![Screenshot 2025-01-02 at 10 12 00](https://github.com/user-attachments/assets/93d03997-78a2-4a4b-a0b0-61083687e9f7)

Safari:
<img width="1678" alt="Screenshot 2025-01-02 at 10 09 52" src="https://github.com/user-attachments/assets/d22d124a-5e3d-4103-889f-b527597cf71e" />

2025-01-02 10:54 UTC, HelenHarlow commented
@rightsaidjames, yeah, the screenshot was taken in Chrome. I've just had a look on Safari, and the spacing is also fine there for me, although the lot picker and image border look a bit funky. I'm not sure what's going on there!
<img width="1438" alt="Screenshot 2025-01-02 at 10 53 52" src="https://github.com/user-attachments/assets/defc8fe2-4ccc-4200-a9ce-6e24725733a4" />

2025-01-02 10:59 UTC, rightsaidjames commented
Sounds like Jamie has a fun puzzle to come back to, then 😄

2025-01-06 15:46 UTC, orangemug commented
@HelenHarlow would you mind retesting this? (new version of safari)

@rightsaidjames can I get some of your time, I also can't see the issues you're seeing.

2025-01-06 16:18 UTC, HelenHarlow approved these changes
I've updated my OS and all looks good in Chrome and Safari for me now :)

2025-01-07 10:13 UTC, rightsaidjames approved these changes
LGTM!

The missing gap between the lot picker and the poster image appears, incredibly, to be influenced by whether hardware/graphics acceleration is enabled in Chrome/Firefox!

<img width="842" alt="Screenshot 2025-01-07 at 10 09 18" src="https://github.com/user-attachments/assets/a45871ab-6e0e-43b4-b405-c36d6ae51bd7" />

When the above setting is disabled, the gap is a reasonable size across all desktop breakpoints:
<img width="1440" alt="Screenshot 2025-01-07 at 10 06 45" src="https://github.com/user-attachments/assets/c2d051dc-ffed-4110-8546-2f63ff17cc26" />

As such, this is a low-level rendering bug that is beyond our control; we should not invest time in fixing it, at least not at this stage. It doesn't have any material impact on the function of the page, and it can't be consistently reproduced on different machines despite near-identical setups.

2025-01-07 10:55 UTC, merged